<h1>Exploring & Preparing The Datasets</h1>

Author of this notebook: Resia S. Kilic

In [ ]:
# Importing pandas to use its functions
import pandas as pd

In [105]:
# Assigning the dataset local path to a variable
# Reading the excel file with pandas
sales_dt = pd.read_excel("sales.xlsx")
metaclean_dt = pd.read_excel("metaClean43Brightspace.xlsx")
#user_dt = pd.read_excel("UserReviewsClean43LIWC.xlsx")
#expert_dt = pd.read_excel("ExpertReviewsClean43LIWC.xlsx")

# Viewining the column names and their data type of sales original dt
sales_dt.info()

# Viewing the first five rows of sales original dataset
sales_dt.head()

<class 'pandas.DataFrame'>
RangeIndex: 30612 entries, 0 to 30611
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   year                      30612 non-null  int64
 1   release_date              30612 non-null  str
 2   title                     30604 non-null  object
 3   genre                     28908 non-null  str
 4   international_box_office  21575 non-null  float64
 5   domestic_box_office       11884 non-null  float64
 6   worldwide_box_office      21575 non-null  float64
 7   production_budget         4480 non-null   float64
 8   opening_weekend           10929 non-null  float64
 9   theatre_count             10963 non-null  float64
 10  avg run per theatre       10952 non-null  float64
 11  runtime                   24559 non-null  float64
 12  keywords                  12517 non-null  object
 13  creative_type             26667 non-null  str
 14  url                       30612 non-null  str
dtypes: float64(8), int64(1), object(2), str(4)
memory usage: 3.5+ MB

,year,release_date,title,genre,international_box_office,domestic_box_office,worldwide_box_office,production_budget,opening_weekend,theatre_count,avg run per theatre,runtime,keywords,creative_type,url
0,2000,January 1st,Bakha Satang,Drama,76576.0,NaN,76576.0,NaN,NaN,NaN,NaN,129.0,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Bakha-Satang...
1,2001,January 12th,Antitrust,Thriller/Suspense,6900000.0,10965209.0,17865209.0,30000000.0,5486209.0,2433.0,3.1,NaN,NaN,Contemporary Fiction,https://www.the-numbers.com/movie/Antitrust
2,2000,January 28th,Santitos,NaN,NaN,378562.0,NaN,NaN,NaN,NaN,NaN,105.0,NaN,NaN,https://www.the-numbers.com/movie/Santitos
3,2002,2002 (Wide) by,Frank McKlusky C.I.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.the-numbers.com/movie/Frank-McKlus...
4,2002,January 25th,A Walk to Remember,Drama,4833792.0,41227069.0,46060861.0,11000000.0,12177488.0,2411.0,5.3,NaN,Coming of Age,Contemporary Fiction,https://www.the-numbers.com/movie/Walk-to-Reme...

In [106]:
# Viewining the column names and their data type of original metaclean dataset
metaclean_dt.info()

# Viewing the first five rows of metaclean original dataset
metaclean_dt.head()

<class 'pandas.DataFrame'>
RangeIndex: 11364 entries, 0 to 11363
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   url        11364 non-null  str
 1   title      11364 non-null  str
 2   studio     11014 non-null  str
 3   rating     10297 non-null  str
 4   runtime    11109 non-null  float64
 5   cast       7662 non-null   str
 6   director   11350 non-null  str
 7   genre      11344 non-null  str
 8   summary    5467 non-null   str
 9   awards     4387 non-null   str
 10  metascore  11364 non-null  int64
 11  userscore  9259 non-null   float64
 12  RelDate    11364 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(9)
memory usage: 1.1 MB

,url,title,studio,rating,runtime,cast,director,genre,summary,awards,metascore,userscore,RelDate
0,https://www.metacritic.com/movie/!women-art-re...,!Women Art Revolution,Hotwire Productions,| Not Rated,83.0,NaN,Lynn Hershman-Leeson,Documentary,NaN,NaN,70,NaN,2011-06-01
1,https://www.metacritic.com/movie/10-cloverfiel...,10 Cloverfield Lane,Paramount Pictures,| PG-13,104.0,"John Gallagher Jr.,John Goodman,Mary Elizabeth...",Dan Trachtenberg,"Action,Sci-Fi,Drama,Mystery,Thriller,Horror","Waking up from a car accident, a young woman (...","#18MostDiscussedMovieof2016 , #1MostSharedMovi...",76,7.7,2016-03-11
2,https://www.metacritic.com/movie/10-items-or-less,10 Items or Less,Click Star,| R,82.0,"Jonah Hill,Morgan Freeman,Paz Vega",Brad Silberling,"Drama,Comedy,Romance",While researching a role as a supermarket mana...,NaN,54,5.8,2006-12-01
3,https://www.metacritic.com/movie/10-years,10 Years,Anchor Bay Entertainment,| R,100.0,"Channing Tatum,Chris Pratt,Jenna Dewan",Jamie Linden,"Drama,Comedy,Romance",NaN,NaN,61,6.9,2012-09-14
4,https://www.metacritic.com/movie/100-bloody-acres,100 Bloody Acres,Music Box Films,| Not Rated,91.0,NaN,Cameron Cairnes,"Horror,Comedy",Reg and Lindsay run an organic fertilizer busi...,NaN,63,7.5,2013-06-28

<h3>Profile MetaClean and Sales dataset</h3>

In [107]:
# Checking row and column counts of Sales and Metaclean
print("MetaClean rows and columns:", metaclean_dt.shape)
print("Sales rows and columns:", sales_dt.shape)

MetaClean rows and columns: (11364, 13)
Sales rows and columns: (30612, 15)

In [108]:
# Checking missing values
print("MetaClean missing values:\n" , metaclean_dt.isnull().sum())

print("MetaClean total missing values:\n" , sum(metaclean_dt.isnull().sum()))

MetaClean missing values:
 url             0
title           0
studio        350
rating       1067
runtime       255
cast         3702
director       14
genre          20
summary      5897
awards       6977
metascore       0
userscore    2105
RelDate         0
dtype: int64
MetaClean total missing values:
 20387

In [109]:
# Checking missing values
print("Sales missing values:\n" , sales_dt.isnull().sum())

print("Sales total missing values:\n" , sum(sales_dt.isnull().sum()))

Sales missing values:
 year                            0
release_date                    0
title                           8
genre                        1704
international_box_office     9037
domestic_box_office         18728
worldwide_box_office         9037
production_budget           26132
opening_weekend             19683
theatre_count               19649
avg run per theatre         19660
runtime                      6053
keywords                    18095
creative_type                3945
url                             0
dtype: int64
Sales total missing values:
 151731

<h3>Checking duplicate records</h3>

In [110]:
# Checking for duplicated rows
print("Sales duplicated rows:", sales_dt.duplicated().sum())
print("MetaClean duplicated rows:", metaclean_dt.duplicated().sum())

Sales duplicated rows: 0
MetaClean duplicated rows: 0

In [111]:
# Checking duplicate URLs
print("Sales duplicate URLs:", sales_dt["url"].duplicated().sum())
print("MetaClean duplicate URLs:", metaclean_dt["url"].duplicated().sum())

Sales duplicate URLs: 0
MetaClean duplicate URLs: 0

<h3>Creating cleaned datasets</h3>

In [112]:
# Create working copies
sales_clean = sales_dt.copy()
metaclean_clean = metaclean_dt.copy()

# Removing the temporary columns used only for matching/checking above
sales_clean = sales_clean.drop(
    columns=["URL_clean", "title_match", "title_year_match"],
    errors="ignore"
)

metaclean_clean = metaclean_clean.drop(
    columns=["URL_clean", "title_match", "year_match"],
    errors="ignore"
)

<h3>Text cleaning</h3>

In [113]:
# Remove unnecessary spaces from text columns
for df in [sales_clean, metaclean_clean]:
    text_columns = df.select_dtypes(include=["object", "string"]).columns
    
    for col in text_columns:
        df[col] = df[col].str.strip()

<h3>Turning empty text cells into proper missing values</h3>

In [114]:
# Converting the empty strings to missing values
for df in [sales_clean, metaclean_clean]:
    df.replace("", pd.NA, inplace=True)

In [115]:
# Checking what I have until now
print("Sales shape:", sales_clean.shape)
print("MetaClean shape:", metaclean_clean.shape)

print("\nSales columns:")
print(sales_clean.columns.tolist())

print("\nMetaClean columns:")
print(metaclean_clean.columns.tolist())

Sales shape: (30612, 15)
MetaClean shape: (11364, 13)

Sales columns:
['year', 'release_date', 'title', 'genre', 'international_box_office', 'domestic_box_office', 'worldwide_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'runtime', 'keywords', 'creative_type', 'url']

MetaClean columns:
['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'RelDate']

<h4>URL overlap investigation</h4>

In [116]:
# Checking if URLs overlap between Sales and MetaClean

print("Sales URLs:", sales_clean["url"].nunique())
print("MetaClean URLs:", metaclean_clean["url"].nunique())

Sales URLs: 30612
MetaClean URLs: 11364

<h3>Title-year matching experiments</h3>

In [117]:
# Prepare title and year columns for matching

sales_clean["title_match"] = (
    sales_clean["title"]
    .astype("string")
    .str.strip()
    .str.lower()
)

metaclean_clean["title_match"] = (
    metaclean_clean["title"]
    .astype("string")
    .str.strip()
    .str.lower()
)

metaclean_clean["year_match"] = metaclean_clean["RelDate"].dt.year

print("Sales title_match created:", "title_match" in sales_clean.columns)
print("MetaClean title_match created:", "title_match" in metaclean_clean.columns)
print("MetaClean year_match created:", "year_match" in metaclean_clean.columns)

Sales title_match created: True
MetaClean title_match created: True
MetaClean year_match created: True

In [118]:
#Count unique Sales-MetaClean title/year matches

sales_match_test = sales_clean.merge(
    metaclean_clean[["title_match", "year_match", "url"]],
    left_on=["title_match", "year"],
    right_on=["title_match", "year_match"],
    how="inner",
    suffixes=("_sales", "_meta")
)

print("Total matched rows:", len(sales_match_test))

print(
    "Unique Sales URLs matched:",
    sales_match_test["url_sales"].nunique()
)

print(
    "Unique MetaClean URLs matched:",
    sales_match_test["url_meta"].nunique()
)

Total matched rows: 8007
Unique Sales URLs matched: 8001
Unique MetaClean URLs matched: 7991

In [119]:
# Find title + year combinations that create multiple matches

# Test title + year matching

match_counts = (
    sales_match_test
    .groupby(["title_match", "year"])
    .agg(
        sales_urls=("url_sales", "nunique"),
        metacritic_urls=("url_meta", "nunique")
    )
    .reset_index()
)

problem_matches = match_counts[
    (match_counts["sales_urls"] > 1) |
    (match_counts["metacritic_urls"] > 1)
]

print("Problematic title + year matches:", len(problem_matches))

print(problem_matches.to_string(index=False))

Problematic title + year matches: 13
      title_match  year  sales_urls  metacritic_urls
        aftermath  2014           2                1
        dreamland  2020           3                2
            greta  2019           2                1
             luca  2021           2                1
              run  2020           2                1
        swan song  2021           2                2
       the hunter  2012           1                2
  the interpreter  2005           2                1
     the outsider  2018           2                1
           thirst  2009           2                1
              val  2021           2                1
      white noise  2005           2                1
wuthering heights  2012           2                1

In [120]:
sales_match_test[
    ["title_match", "year", "url_sales", "url_meta"]
].head(20)

,title_match,year,url_sales,url_meta
0,antitrust,2001,https://www.the-numbers.com/movie/Antitrust,https://www.metacritic.com/movie/antitrust
1,santitos,2000,https://www.the-numbers.com/movie/Santitos,https://www.metacritic.com/movie/santitos
2,a walk to remember,2002,https://www.the-numbers.com/movie/Walk-to-Reme...,https://www.metacritic.com/movie/a-walk-to-rem...
3,the killing of john lennon,2008,https://www.the-numbers.com/movie/Killing-of-J...,https://www.metacritic.com/movie/the-killing-o...
4,mad money,2008,https://www.the-numbers.com/movie/Mad-Money,https://www.metacritic.com/movie/mad-money
5,over her dead body,2008,https://www.the-numbers.com/movie/Over-Her-Dea...,https://www.metacritic.com/movie/over-her-dead...
6,the other boleyn girl,2008,https://www.the-numbers.com/movie/Other-Boleyn...,https://www.metacritic.com/movie/the-other-bol...
7,pariah,2011,https://www.the-numbers.com/movie/Pariah-(2011),https://www.metacritic.com/movie/pariah
8,war horse,2011,https://www.the-numbers.com/movie/War-Horse,https://www.metacritic.com/movie/war-horse
9,extremely loud and incredibly close,2011,https://www.the-numbers.com/movie/Extremely-Lo...,https://www.metacritic.com/movie/extremely-lou...
10,angels crest,2011,https://www.the-numbers.com/movie/Angels-Crest,https://www.metacritic.com/movie/angels-crest
11,the darkest hour,2011,https://www.the-numbers.com/movie/Darkest-Hour...,https://www.metacritic.com/movie/the-darkest-hour
12,miss minoes,2011,https://www.the-numbers.com/movie/Miss-Minoes,https://www.metacritic.com/movie/miss-minoes
13,we bought a zoo,2011,https://www.the-numbers.com/movie/We-Bought-a-Zoo,https://www.metacritic.com/movie/we-bought-a-zoo
14,in the land of blood and honey,2011,https://www.the-numbers.com/movie/In-The-Land-...,https://www.metacritic.com/movie/in-the-land-o...
15,we are the giant,2014,https://www.the-numbers.com/movie/We-Are-the-G...,https://www.metacritic.com/movie/we-are-the-giant
16,meru,2015,https://www.the-numbers.com/movie/Meru,https://www.metacritic.com/movie/meru
17,welcome to leith,2015,https://www.the-numbers.com/movie/Welcome-to-L...,https://www.metacritic.com/movie/welcome-to-leith
18,truth,2015,https://www.the-numbers.com/movie/Truth-(2015),https://www.metacritic.com/movie/truth-2015
19,point break,2015,https://www.the-numbers.com/movie/Point-Break-...,https://www.metacritic.com/movie/point-break-2015

In [121]:
# Inspect ambiguous Sales records

ambiguous_titles = problem_matches["title_match"].tolist()

sales_ambiguous = sales_clean[
    sales_clean["title_match"].isin(ambiguous_titles)
].sort_values(["title_match", "year"])

print(
    sales_ambiguous[
        ["title", "year", "runtime", "genre", "url"]
    ].to_string(index=False)
)

            title  year  runtime             genre                                                                           url
        Aftermath  2014     84.0      Black Comedy                            https://www.the-numbers.com/movie/Aftermath-(2013)
        Aftermath  2014      NaN            Horror                            https://www.the-numbers.com/movie/Aftermath-(2012)
        Aftermath  2017     92.0 Thriller/Suspense                            https://www.the-numbers.com/movie/Aftermath-(2016)
        Dreamland  2006      NaN               NaN                            https://www.the-numbers.com/movie/Dreamland-(2006)
        Dreamland  2016     89.0            Comedy                            https://www.the-numbers.com/movie/Dreamland-(2016)
        Dreamland  2020    118.0 Thriller/Suspense                            https://www.the-numbers.com/movie/Dreamland-(2020)
        Dreamland  2020    101.0 Thriller/Suspense https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)
        Dreamland  2020     92.0      Black Comedy                          https://www.the-numbers.com/movie/Dreamland-(Canada)
            Greta  2019     97.0             Drama                              https://www.the-numbers.com/movie/Greta-(Brazil)
            Greta  2019     98.0 Thriller/Suspense                                https://www.the-numbers.com/movie/Greta-(2019)
             Luca  2019    151.0   Romantic Comedy                                https://www.the-numbers.com/movie/Luca-(India)
             Luca  2021     95.0         Adventure                                 https://www.the-numbers.com/movie/Luca-(2021)
             Luca  2021    105.0 Thriller/Suspense                         https://www.the-numbers.com/movie/Luca-(2021-Romania)
              Run  2004      NaN               NaN                                  https://www.the-numbers.com/movie/Run-(2004)
              Run  2019     97.0         Adventure                       https://www.the-numbers.com/movie/Run-(Bulgaria)-(2019)
              Run  2020      NaN Thriller/Suspense                                  https://www.the-numbers.com/movie/Run-(2020)
              Run  2020     78.0             Drama                                    https://www.the-numbers.com/movie/Run-(UK)
        Swan Song  2021      NaN             Drama                            https://www.the-numbers.com/movie/Swan-Song-(2021)
        Swan Song  2021    105.0             Drama          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)
       The Hunter  2012    101.0             Drama                           https://www.the-numbers.com/movie/Hunter-The-(2011)
  The Interpreter  2005    128.0 Thriller/Suspense                      https://www.the-numbers.com/movie/Interpreter-The-(2005)
  The Interpreter  2005    113.0               NaN           https://www.the-numbers.com/movie/Interpreter-The-(Slovakia)-(2018)
     The Outsider  2014     94.0            Action                         https://www.the-numbers.com/movie/Outsider-The-(2014)
     The Outsider  2018     99.0       Documentary          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)
     The Outsider  2018    120.0            Action                         https://www.the-numbers.com/movie/Outsider-The-(2018)
           Thirst  2009     91.0            Horror                               https://www.the-numbers.com/movie/Thirst-(2009)
           Thirst  2009      NaN            Horror                                      https://www.the-numbers.com/movie/Thirst
              Val  2021     81.0            Comedy                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)
              Val  2021    109.0       Documentary                      https://www.the-numbers.com/movie/Val-(2021-Documentary)
      White Noise  2005     94.0       Documentary                          https://www.the-numbers.com/movie/White-Noise-(2020)
      White Noise  2005    101.0            Horror                          https://www.the-numbers.com/movie/White-Noise-(2005)
Wuthering Heights  2012    128.0             Drama                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)
Wuthering Heights  2012    142.0       Documentary                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)

In [122]:
# Inspect ambiguous MetaClean records

meta_ambiguous = metaclean_clean[
    metaclean_clean["title_match"].isin(ambiguous_titles)
].sort_values(["title_match", "year_match"])

print(
    meta_ambiguous[
        ["title", "year_match", "RelDate", "url", "director"]
    ].to_string(index=False)
)

            title  year_match    RelDate                                                url               director
        Aftermath        2013 2013-11-01         https://www.metacritic.com/movie/aftermath   Wladyslaw Pasikowski
        Aftermath        2014 2014-07-18    https://www.metacritic.com/movie/aftermath-2014           Peter Engert
        Aftermath        2017 2017-04-07    https://www.metacritic.com/movie/aftermath-2017         Elliott Lester
        Dreamland        2020 2020-11-13    https://www.metacritic.com/movie/dreamland-2019 Miles Joris-Peyrafitte
        Dreamland        2020 2020-06-05    https://www.metacritic.com/movie/dreamland-2020         Bruce McDonald
            Greta        2019 2019-03-01             https://www.metacritic.com/movie/greta            Neil Jordan
             Luca        2021 2021-06-18              https://www.metacritic.com/movie/luca        Enrico Casarosa
              Run        2020 2020-11-20               https://www.metacritic.com/movie/run        Aneesh Chaganty
        Swan Song        2021 2021-08-06         https://www.metacritic.com/movie/swan-song          Todd Stephens
        Swan Song        2021 2021-12-17    https://www.metacritic.com/movie/swan-song-2021        Benjamin Cleary
       The Hunter        2012 2012-01-04        https://www.metacritic.com/movie/the-hunter             Rafi Pitts
       The Hunter        2012 2012-04-06   https://www.metacritic.com/movie/the-hunter-2012        Daniel Nettheim
  The Interpreter        2005 2005-04-22   https://www.metacritic.com/movie/the-interpreter         Sydney Pollack
     The Outsider        2006 2006-04-07      https://www.metacritic.com/movie/the-outsider       Nicholas Jarecki
     The Outsider        2014 2014-02-07 https://www.metacritic.com/movie/the-outsider-2014        Brian A. Miller
     The Outsider        2018 2018-03-09 https://www.metacritic.com/movie/the-outsider-2018       Martin Zandvliet
           Thirst        2009 2009-07-31            https://www.metacritic.com/movie/thirst         Chan-wook Park
              Val        2021 2021-07-23               https://www.metacritic.com/movie/val              Leo Scott
      White Noise        2005 2005-01-07       https://www.metacritic.com/movie/white-noise           Geoffrey Sax
Wuthering Heights        2012 2012-10-05 https://www.metacritic.com/movie/wuthering-heights          Andrea Arnold

In [123]:
sales_ambiguous_details = sales_clean[
    sales_clean["title_match"].isin(ambiguous_titles)
].sort_values(["title_match", "year"])

print(
    sales_ambiguous_details[
        ["title", "year", "runtime", "genre", "creative_type", "url"]
    ].to_string(index=False)
)

            title  year  runtime             genre        creative_type                                                                           url
        Aftermath  2014     84.0      Black Comedy Contemporary Fiction                            https://www.the-numbers.com/movie/Aftermath-(2013)
        Aftermath  2014      NaN            Horror      Science Fiction                            https://www.the-numbers.com/movie/Aftermath-(2012)
        Aftermath  2017     92.0 Thriller/Suspense        Dramatization                            https://www.the-numbers.com/movie/Aftermath-(2016)
        Dreamland  2006      NaN               NaN                  NaN                            https://www.the-numbers.com/movie/Dreamland-(2006)
        Dreamland  2016     89.0            Comedy Contemporary Fiction                            https://www.the-numbers.com/movie/Dreamland-(2016)
        Dreamland  2020    118.0 Thriller/Suspense Contemporary Fiction                            https://www.the-numbers.com/movie/Dreamland-(2020)
        Dreamland  2020    101.0 Thriller/Suspense   Historical Fiction https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)
        Dreamland  2020     92.0      Black Comedy              Fantasy                          https://www.the-numbers.com/movie/Dreamland-(Canada)
            Greta  2019     97.0             Drama Contemporary Fiction                              https://www.the-numbers.com/movie/Greta-(Brazil)
            Greta  2019     98.0 Thriller/Suspense Contemporary Fiction                                https://www.the-numbers.com/movie/Greta-(2019)
             Luca  2019    151.0   Romantic Comedy Contemporary Fiction                                https://www.the-numbers.com/movie/Luca-(India)
             Luca  2021     95.0         Adventure         Kids Fiction                                 https://www.the-numbers.com/movie/Luca-(2021)
             Luca  2021    105.0 Thriller/Suspense   Historical Fiction                         https://www.the-numbers.com/movie/Luca-(2021-Romania)
              Run  2004      NaN               NaN                  NaN                                  https://www.the-numbers.com/movie/Run-(2004)
              Run  2019     97.0         Adventure Contemporary Fiction                       https://www.the-numbers.com/movie/Run-(Bulgaria)-(2019)
              Run  2020      NaN Thriller/Suspense Contemporary Fiction                                  https://www.the-numbers.com/movie/Run-(2020)
              Run  2020     78.0             Drama Contemporary Fiction                                    https://www.the-numbers.com/movie/Run-(UK)
        Swan Song  2021      NaN             Drama      Science Fiction                            https://www.the-numbers.com/movie/Swan-Song-(2021)
        Swan Song  2021    105.0             Drama Contemporary Fiction          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)
       The Hunter  2012    101.0             Drama Contemporary Fiction                           https://www.the-numbers.com/movie/Hunter-The-(2011)
  The Interpreter  2005    128.0 Thriller/Suspense Contemporary Fiction                      https://www.the-numbers.com/movie/Interpreter-The-(2005)
  The Interpreter  2005    113.0               NaN Contemporary Fiction           https://www.the-numbers.com/movie/Interpreter-The-(Slovakia)-(2018)
     The Outsider  2014     94.0            Action Contemporary Fiction                         https://www.the-numbers.com/movie/Outsider-The-(2014)
     The Outsider  2018     99.0       Documentary              Factual          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)
     The Outsider  2018    120.0            Action   Historical Fiction                         https://www.the-numbers.com/movie/Outsider-The-(2018)
           Thirst  2009     91.0            Horror Contemporary Fiction                               https://www.the-numbers.com/movie/Thirst-(2009)
           Thirst  2009      NaN            Horror              Fantasy                                      https://www.the-numbers.com/movie/Thirst
              Val  2021     81.0            Comedy Contemporary Fiction                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)
              Val  2021    109.0       Documentary              Factual                      https://www.the-numbers.com/movie/Val-(2021-Documentary)
      White Noise  2005     94.0       Documentary              Factual                          https://www.the-numbers.com/movie/White-Noise-(2020)
      White Noise  2005    101.0            Horror Contemporary Fiction                          https://www.the-numbers.com/movie/White-Noise-(2005)
Wuthering Heights  2012    128.0             Drama   Historical Fiction                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)
Wuthering Heights  2012    142.0       Documentary   Historical Fiction                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)

In [124]:
meta_ambiguous_details = metaclean_clean[
    metaclean_clean["title_match"].isin(ambiguous_titles)
].sort_values(["title_match", "year_match"])

print(
    meta_ambiguous_details[
        ["title", "year_match", "runtime", "genre", "director", "url"]
    ].to_string(index=False)
)

            title  year_match  runtime                                     genre               director                                                url
        Aftermath        2013    107.0                            Drama,Thriller   Wladyslaw Pasikowski         https://www.metacritic.com/movie/aftermath
        Aftermath        2014     92.0                           Action,Thriller           Peter Engert    https://www.metacritic.com/movie/aftermath-2014
        Aftermath        2017     94.0                            Drama,Thriller         Elliott Lester    https://www.metacritic.com/movie/aftermath-2017
        Dreamland        2020     98.0                            Drama,Thriller Miles Joris-Peyrafitte    https://www.metacritic.com/movie/dreamland-2019
        Dreamland        2020     92.0               Fantasy,Horror,Comedy,Crime         Bruce McDonald    https://www.metacritic.com/movie/dreamland-2020
            Greta        2019     98.0             Drama,Mystery,Thriller,Horror            Neil Jordan             https://www.metacritic.com/movie/greta
             Luca        2021     95.0 Adventure,Fantasy,Comedy,Animation,Family        Enrico Casarosa              https://www.metacritic.com/movie/luca
              Run        2020     90.0                   Mystery,Thriller,Horror        Aneesh Chaganty               https://www.metacritic.com/movie/run
        Swan Song        2021    105.0                                     Drama          Todd Stephens         https://www.metacritic.com/movie/swan-song
        Swan Song        2021    116.0                              Sci-Fi,Drama        Benjamin Cleary    https://www.metacritic.com/movie/swan-song-2021
       The Hunter        2012     90.0                                  Thriller             Rafi Pitts        https://www.metacritic.com/movie/the-hunter
       The Hunter        2012    100.0                           Adventure,Drama        Daniel Nettheim   https://www.metacritic.com/movie/the-hunter-2012
  The Interpreter        2005    128.0                    Drama,Mystery,Thriller         Sydney Pollack   https://www.metacritic.com/movie/the-interpreter
     The Outsider        2006     85.0                               Documentary       Nicholas Jarecki      https://www.metacritic.com/movie/the-outsider
     The Outsider        2014     94.0       Action,Drama,Mystery,Thriller,Crime        Brian A. Miller https://www.metacritic.com/movie/the-outsider-2014
     The Outsider        2018    120.0              Drama,Mystery,Thriller,Crime       Martin Zandvliet https://www.metacritic.com/movie/the-outsider-2018
           Thirst        2009    133.0                      Drama,Horror,Romance         Chan-wook Park            https://www.metacritic.com/movie/thirst
              Val        2021    109.0                               Documentary              Leo Scott               https://www.metacritic.com/movie/val
      White Noise        2005    101.0      Sci-Fi,Drama,Mystery,Thriller,Horror           Geoffrey Sax       https://www.metacritic.com/movie/white-noise
Wuthering Heights        2012    129.0                             Drama,Romance          Andrea Arnold https://www.metacritic.com/movie/wuthering-heights

<h4>Title - Year counts</h4>

In [125]:
title_year_counts = (
    sales_clean
    .groupby(["title_match", "year"])
    .size()
    .reset_index(name="sales_count")
)

meta_title_year_counts = (
    metaclean_clean
    .groupby(["title_match", "year_match"])
    .size()
    .reset_index(name="meta_count")
)

unique_title_year_matches = (
    title_year_counts[title_year_counts["sales_count"] == 1]
    .merge(
        meta_title_year_counts[meta_title_year_counts["meta_count"] == 1],
        left_on=["title_match", "year"],
        right_on=["title_match", "year_match"],
        how="inner"
    )
)

print("Unique title + year matches:",
      len(unique_title_year_matches))

Unique title + year matches: 7975

<h2>Create the Movie table</h2>

In [126]:
movie = metaclean_clean[
    ["url", "title", "year_match"]
].copy()

movie = movie.rename(columns={
    "year_match": "year"
})

print(movie.shape)
print(movie.head())

(11364, 3)
                                                 url                  title  \
0  https://www.metacritic.com/movie/!women-art-re...  !Women Art Revolution
1  https://www.metacritic.com/movie/10-cloverfiel...    10 Cloverfield Lane
2  https://www.metacritic.com/movie/10-items-or-less       10 Items or Less
3          https://www.metacritic.com/movie/10-years               10 Years
4  https://www.metacritic.com/movie/100-bloody-acres       100 Bloody Acres

   year
0  2011
1  2016
2  2006
3  2012
4  2013

In [127]:
# Checking whether each Movie URL is unique
print("Duplicate movie URLs:", movie["url"].duplicated().sum())
print("Missing movie URLs:", movie["url"].isna().sum())

Duplicate movie URLs: 0
Missing movie URLs: 0

In [128]:
# creating movie_id
movie = movie.reset_index(drop=True)

movie.insert(
    0,
    "movie_id",
    range(1, len(movie) + 1)
)

print(movie.head())
print("\nNumber of movie IDs:", movie["movie_id"].nunique())
print("Number of movies:", len(movie))

   movie_id                                                url  \
0         1  https://www.metacritic.com/movie/!women-art-re...
1         2  https://www.metacritic.com/movie/10-cloverfiel...
2         3  https://www.metacritic.com/movie/10-items-or-less
3         4          https://www.metacritic.com/movie/10-years
4         5  https://www.metacritic.com/movie/100-bloody-acres

                   title  year
0  !Women Art Revolution  2011
1    10 Cloverfield Lane  2016
2       10 Items or Less  2006
3               10 Years  2012
4       100 Bloody Acres  2013

Number of movie IDs: 11364
Number of movies: 11364

In [129]:
print(movie.isna().sum())
#checking for missing values

movie_id    0
url         0
title       0
year        0
dtype: int64

In [130]:
print(metaclean_clean.columns.tolist())

['url', 'title', 'studio', 'rating', 'runtime', 'cast', 'director', 'genre', 'summary', 'awards', 'metascore', 'userscore', 'RelDate', 'title_match', 'year_match']

In [131]:
movie_csv = movie[
    ["movie_id", "url", "title", "year"]
].copy()

print(movie_csv.head())
print(movie_csv.shape)
print("Unique movie IDs:", movie_csv["movie_id"].nunique())

   movie_id                                                url  \
0         1  https://www.metacritic.com/movie/!women-art-re...
1         2  https://www.metacritic.com/movie/10-cloverfiel...
2         3  https://www.metacritic.com/movie/10-items-or-less
3         4          https://www.metacritic.com/movie/10-years
4         5  https://www.metacritic.com/movie/100-bloody-acres

                   title  year
0  !Women Art Revolution  2011
1    10 Cloverfield Lane  2016
2       10 Items or Less  2006
3               10 Years  2012
4       100 Bloody Acres  2013
(11364, 4)
Unique movie IDs: 11364

In [132]:
movie_csv.to_csv("Movie.csv", index=False, encoding="utf-8-sig")
print("Movie.csv created successfully.")

Movie.csv created successfully.

<h2>Movie_Sales preperation</h2>

In [133]:
# Preparing Sales records for Movie_Sales

sales_for_movie_sales = sales_clean[
    [
        "url",
        "title_match",
        "year",
        "worldwide_box_office",
        "domestic_box_office",
        "international_box_office",
        "production_budget",
        "opening_weekend",
        "theatre_count",
        "avg run per theatre"
    ]
].copy()

print("Sales records:", len(sales_for_movie_sales))
print(sales_for_movie_sales.head())

Sales records: 30612
                                                 url          title_match  \
0  https://www.the-numbers.com/movie/Bakha-Satang...         bakha satang
1        https://www.the-numbers.com/movie/Antitrust            antitrust
2         https://www.the-numbers.com/movie/Santitos             santitos
3  https://www.the-numbers.com/movie/Frank-McKlus...  frank mcklusky c.i.
4  https://www.the-numbers.com/movie/Walk-to-Reme...   a walk to remember

   year  worldwide_box_office  domestic_box_office  international_box_office  \
0  2000               76576.0                  NaN                   76576.0
1  2001            17865209.0           10965209.0                 6900000.0
2  2000                   NaN             378562.0                       NaN
3  2002                   NaN                  NaN                       NaN
4  2002            46060861.0           41227069.0                 4833792.0

   production_budget  opening_weekend  theatre_count  avg run per theatre
0                NaN              NaN            NaN                  NaN
1         30000000.0        5486209.0         2433.0                  3.1
2                NaN              NaN            NaN                  NaN
3                NaN              NaN            NaN                  NaN
4         11000000.0       12177488.0         2411.0                  5.3

In [134]:
# Matching Sales records to the Movie table

sales_movie_sales = sales_for_movie_sales.merge(
    movie[["movie_id", "title", "year"]],
    left_on=["title_match", "year"],
    right_on=[
        movie["title"].astype("string").str.strip().str.lower(),
        "year"
    ],
    how="inner"
)

print("Matched Sales records:", len(sales_movie_sales))
print("Unique movies matched:", sales_movie_sales["movie_id"].nunique())
print(sales_movie_sales.head())

Matched Sales records: 8007
Unique movies matched: 7991
                                                 url  \
0        https://www.the-numbers.com/movie/Antitrust
1         https://www.the-numbers.com/movie/Santitos
2  https://www.the-numbers.com/movie/Walk-to-Reme...
3  https://www.the-numbers.com/movie/Killing-of-J...
4        https://www.the-numbers.com/movie/Mad-Money

                  title_match  year  worldwide_box_office  \
0                   antitrust  2001            17865209.0
1                    santitos  2000                   NaN
2          a walk to remember  2002            46060861.0
3  the killing of john lennon  2008                   NaN
4                   mad money  2008            25044057.0

   domestic_box_office  international_box_office  production_budget  \
0           10965209.0                 6900000.0         30000000.0
1             378562.0                       NaN                NaN
2           41227069.0                 4833792.0         11000000.0
3               6975.0                       NaN                NaN
4           20668843.0                 4375214.0         22000000.0

   opening_weekend  theatre_count  avg run per theatre  movie_id  \
0        5486209.0         2433.0                  3.1       781
1              NaN            NaN                  NaN      7172
2       12177488.0         2411.0                  5.3       366
3           3077.0            1.0                  3.0      9166
4        7736452.0         2470.0                  3.4      5272

                        title
0                   Antitrust
1                    Santitos
2          A Walk to Remember
3  The Killing of John Lennon
4                   Mad Money

In [135]:
# Checking how many Sales records are linked to each movie

sales_counts = (
    sales_movie_sales
    .groupby("movie_id")
    .size()
    .sort_values(ascending=False)
)

print("Sales records per movie:")
print(sales_counts.value_counts().sort_index())

print("\nMovies with multiple Sales records:")
print(sales_counts[sales_counts > 1])

Sales records per movie:
1    7977
2      12
3       2
Name: count, dtype: int64

Movies with multiple Sales records:
movie_id
2626     3
2627     3
3596     2
475      2
5223     2
7100     2
7976     2
7977     2
9111     2
9558     2
10265    2
10706    2
11065    2
11229    2
dtype: int64

In [136]:
# inspecting movies with multiple Sales records

duplicate_movie_ids = sales_counts[sales_counts > 1].index

duplicate_sales = (
    sales_movie_sales[
        sales_movie_sales["movie_id"].isin(duplicate_movie_ids)
    ]
    .sort_values(["movie_id", "url"])
)

print(
    duplicate_sales[
        [
            "movie_id",
            "title",
            "year",
            "url",
            "worldwide_box_office",
            "domestic_box_office",
            "international_box_office",
            "production_budget",
            "opening_weekend",
            "theatre_count",
            "avg run per theatre"
        ]
    ].to_string(index=False)
)

 movie_id             title  year                                                                           url  worldwide_box_office  domestic_box_office  international_box_office  production_budget  opening_weekend  theatre_count  avg run per theatre
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2012)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2013)                   NaN               2955.0                       NaN                NaN           1124.0            1.0                  2.0
     2626         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0             409363.0                  672369.0                NaN         178602.0          216.0                  2.5
     2626         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0                  NaN                  238652.0                NaN              NaN            NaN                  NaN
     2626         Dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
     2627         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0             409363.0                  672369.0                NaN         178602.0          216.0                  2.5
     2627         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0                  NaN                  238652.0                NaN              NaN            NaN                  NaN
     2627         Dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
     3596             Greta  2019                                https://www.the-numbers.com/movie/Greta-(2019)            18745868.0           10544310.0                 8201558.0                NaN        4481910.0         2411.0                  2.6
     3596             Greta  2019                              https://www.the-numbers.com/movie/Greta-(Brazil)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
     5223              Luca  2021                                 https://www.the-numbers.com/movie/Luca-(2021)            49788012.0                  NaN                49788012.0                NaN              NaN            NaN                  NaN
     5223              Luca  2021                         https://www.the-numbers.com/movie/Luca-(2021-Romania)             1002916.0                  NaN                 1002916.0                NaN              NaN            NaN                  NaN
     7100               Run  2020                                  https://www.the-numbers.com/movie/Run-(2020)             4518862.0                  NaN                 4518862.0                NaN              NaN            NaN                  NaN
     7100               Run  2020                                    https://www.the-numbers.com/movie/Run-(UK)                4095.0                  NaN                    4095.0                NaN              NaN            NaN                  NaN
     7976         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
     7976         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)              164802.0             126110.0                   38692.0                NaN          26855.0           35.0                  4.1
     7977         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
     7977         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)              164802.0             126110.0                   38692.0                NaN          26855.0           35.0                  4.1
     9111   The Interpreter  2005                      https://www.the-numbers.com/movie/Interpreter-The-(2005)           162753837.0           72708161.0                90045676.0         90000000.0       22822455.0         2758.0                  5.8
     9111   The Interpreter  2005           https://www.the-numbers.com/movie/Interpreter-The-(Slovakia)-(2018)             5407451.0                  NaN                 5407451.0                NaN              NaN            NaN                  NaN
     9558      The Outsider  2018                         https://www.the-numbers.com/movie/Outsider-The-(2018)                3053.0                  NaN                    3053.0                NaN              NaN            NaN                  NaN
     9558      The Outsider  2018          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
    10265            Thirst  2009                                      https://www.the-numbers.com/movie/Thirst            13468951.0             318574.0                13150377.0                NaN          55889.0            4.0                  2.6
    10265            Thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009)            13158962.0                  NaN                13158962.0                NaN              NaN            NaN                  NaN
    10706               Val  2021                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
    10706               Val  2021                      https://www.the-numbers.com/movie/Val-(2021-Documentary)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005)            92094360.0           56094360.0                36000000.0         10000000.0       24113565.0         2261.0                  4.8
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)             1295735.0                  NaN                 1295735.0                NaN              NaN            NaN                  NaN
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)              460041.0                  NaN                  460041.0                NaN              NaN            NaN                  NaN
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)             2721534.0             100915.0                 2620619.0          8000000.0           8956.0            1.0                  5.8

In [137]:
# we check if these records can be resolved
# Identify country-specific and alternate Sales URLs

duplicate_sales["url_type"] = duplicate_sales["url"].str.extract(
    r"\(([^()]*)\)"
)

print(
    duplicate_sales[
        ["movie_id", "title", "year", "url", "url_type"]
    ].to_string(index=False)
)

 movie_id             title  year                                                                           url                        url_type
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2012)                            2012
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2013)                            2013
     2626         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)                            2020
     2626         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte) 2020-Dir-Miles-Joris-Peyrafitte
     2626         Dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)                          Canada
     2627         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)                            2020
     2627         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte) 2020-Dir-Miles-Joris-Peyrafitte
     2627         Dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)                          Canada
     3596             Greta  2019                                https://www.the-numbers.com/movie/Greta-(2019)                            2019
     3596             Greta  2019                              https://www.the-numbers.com/movie/Greta-(Brazil)                          Brazil
     5223              Luca  2021                                 https://www.the-numbers.com/movie/Luca-(2021)                            2021
     5223              Luca  2021                         https://www.the-numbers.com/movie/Luca-(2021-Romania)                    2021-Romania
     7100               Run  2020                                  https://www.the-numbers.com/movie/Run-(2020)                            2020
     7100               Run  2020                                    https://www.the-numbers.com/movie/Run-(UK)                              UK
     7976         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                            2021
     7976         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)          2021-Dir-Todd-Stephens
     7977         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                            2021
     7977         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)          2021-Dir-Todd-Stephens
     9111   The Interpreter  2005                      https://www.the-numbers.com/movie/Interpreter-The-(2005)                            2005
     9111   The Interpreter  2005           https://www.the-numbers.com/movie/Interpreter-The-(Slovakia)-(2018)                        Slovakia
     9558      The Outsider  2018                         https://www.the-numbers.com/movie/Outsider-The-(2018)                            2018
     9558      The Outsider  2018          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)             2018-United-Kingdom
    10265            Thirst  2009                                      https://www.the-numbers.com/movie/Thirst                             NaN
    10265            Thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009)                            2009
    10706               Val  2021                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)          2021-Dir-Aaron-Fradkin
    10706               Val  2021                      https://www.the-numbers.com/movie/Val-(2021-Documentary)                2021-Documentary
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005)                            2005
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)                            2020
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)                            2009
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)                            2011

In [138]:
worldwide_check = (
    sales_movie_sales
    .groupby("movie_id")
    .agg(
        sales_records=("movie_id", "size"),
        worldwide_records=("worldwide_box_office", "count"),
        worldwide_total=("worldwide_box_office", "sum")
    )
)

print(worldwide_check.head())

print("\nMovies with multiple records but different worldwide values:")
print(
    worldwide_check[
        (worldwide_check["sales_records"] > 1) &
        (worldwide_check["worldwide_records"] > 1)
    ]
)

          sales_records  worldwide_records  worldwide_total
movie_id
2                     1                  1      108286422.0
4                     1                  1         987640.0
5                     1                  0              0.0
9                     1                  1          20452.0
10                    1                  1          47019.0

Movies with multiple records but different worldwide values:
          sales_records  worldwide_records  worldwide_total
movie_id
2626                  3                  2        1320384.0
2627                  3                  2        1320384.0
5223                  2                  2       50790928.0
7100                  2                  2        4522957.0
9111                  2                  2      168161288.0
10265                 2                  2       26627913.0
11065                 2                  2       93390095.0
11229                 2                  2        3181575.0

In [139]:
# inspection of the above cases
problem_movie_ids = worldwide_check[
    (worldwide_check["sales_records"] > 1) &
    (worldwide_check["worldwide_records"] > 1)
].index

problem_worldwide = (
    sales_movie_sales[
        sales_movie_sales["movie_id"].isin(problem_movie_ids)
    ]
    [
        [
            "movie_id",
            "title",
            "year",
            "url",
            "worldwide_box_office"
        ]
    ]
    .sort_values(["movie_id", "url"])
)

print(problem_worldwide.to_string(index=False))

 movie_id             title  year                                                                           url  worldwide_box_office
     2626         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0
     2626         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0
     2626         Dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)                   NaN
     2627         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0
     2627         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0
     2627         Dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)                   NaN
     5223              Luca  2021                                 https://www.the-numbers.com/movie/Luca-(2021)            49788012.0
     5223              Luca  2021                         https://www.the-numbers.com/movie/Luca-(2021-Romania)             1002916.0
     7100               Run  2020                                  https://www.the-numbers.com/movie/Run-(2020)             4518862.0
     7100               Run  2020                                    https://www.the-numbers.com/movie/Run-(UK)                4095.0
     9111   The Interpreter  2005                      https://www.the-numbers.com/movie/Interpreter-The-(2005)           162753837.0
     9111   The Interpreter  2005           https://www.the-numbers.com/movie/Interpreter-The-(Slovakia)-(2018)             5407451.0
    10265            Thirst  2009                                      https://www.the-numbers.com/movie/Thirst            13468951.0
    10265            Thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009)            13158962.0
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005)            92094360.0
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)             1295735.0
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)              460041.0
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)             2721534.0

In [140]:
duplicate_movies = movie[
    movie["movie_id"].isin([2626, 2627, 7976, 7977])
]

print(duplicate_movies.to_string(index=False))

 movie_id                                             url     title  year
     2626 https://www.metacritic.com/movie/dreamland-2019 Dreamland  2020
     2627 https://www.metacritic.com/movie/dreamland-2020 Dreamland  2020
     7976      https://www.metacritic.com/movie/swan-song Swan Song  2021
     7977 https://www.metacritic.com/movie/swan-song-2021 Swan Song  2021

In [141]:
main_sales = sales_movie_sales[
    ~sales_movie_sales["url"].str.contains(
        r"\((Canada|Brazil|UK|Romania|Slovakia|United-Kingdom)\)",
        case=False,
        na=False
    )
].copy()

print("Rows after removing country-specific records:", len(main_sales))

print("\nMovies still having multiple Sales records:")
remaining_counts = main_sales.groupby("movie_id").size()
print(remaining_counts[remaining_counts > 1])

print("\nRemaining duplicate records:")
print(
    main_sales[
        main_sales["movie_id"].isin(
            remaining_counts[remaining_counts > 1].index
        )
    ][
        ["movie_id", "title", "year", "url", "worldwide_box_office"]
    ].to_string(index=False)
)

Rows after removing country-specific records: 7838

Movies still having multiple Sales records:
movie_id
475      2
2626     2
2627     2
5223     2
7976     2
7977     2
9558     2
10265    2
10706    2
11065    2
11229    2
dtype: int64

Remaining duplicate records:
 movie_id             title  year                                                                           url  worldwide_box_office
     9558      The Outsider  2018          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)                   NaN
     9558      The Outsider  2018                         https://www.the-numbers.com/movie/Outsider-The-(2018)                3053.0
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2013)                   NaN
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)             2721534.0
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2012)                   NaN
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)              460041.0
    10265            Thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009)            13158962.0
    10265            Thirst  2009                                      https://www.the-numbers.com/movie/Thirst            13468951.0
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)             1295735.0
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005)            92094360.0
     2626         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0
     2627         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0
     2626         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0
     2627         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0
     7976         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                   NaN
     7977         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                   NaN
    10706               Val  2021                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)                   NaN
     7976         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)              164802.0
     7977         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)              164802.0
    10706               Val  2021                      https://www.the-numbers.com/movie/Val-(2021-Documentary)                   NaN
     5223              Luca  2021                                 https://www.the-numbers.com/movie/Luca-(2021)            49788012.0
     5223              Luca  2021                         https://www.the-numbers.com/movie/Luca-(2021-Romania)             1002916.0

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_29444\3060402079.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ~sales_movie_sales["url"].str.contains(

In [142]:
check_remaining = main_sales[
    main_sales["movie_id"].isin(
        [475, 2626, 2627, 5223, 7976, 7977, 9558, 10265, 10706, 11065, 11229]
    )
].copy()

print(
    check_remaining[
        [
            "movie_id",
            "title",
            "year",
            "url",
            "worldwide_box_office",
            "production_budget",
            "opening_weekend",
            "theatre_count"
        ]
    ].sort_values(["title", "movie_id", "url"]).to_string(index=False)
)

 movie_id             title  year                                                                           url  worldwide_box_office  production_budget  opening_weekend  theatre_count
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2012)                   NaN                NaN              NaN            NaN
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2013)                   NaN                NaN           1124.0            1.0
     2626         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0                NaN         178602.0          216.0
     2626         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0                NaN              NaN            NaN
     2627         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0                NaN         178602.0          216.0
     2627         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0                NaN              NaN            NaN
     5223              Luca  2021                                 https://www.the-numbers.com/movie/Luca-(2021)            49788012.0                NaN              NaN            NaN
     5223              Luca  2021                         https://www.the-numbers.com/movie/Luca-(2021-Romania)             1002916.0                NaN              NaN            NaN
     7976         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                   NaN                NaN              NaN            NaN
     7976         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)              164802.0                NaN          26855.0           35.0
     7977         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                   NaN                NaN              NaN            NaN
     7977         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)              164802.0                NaN          26855.0           35.0
     9558      The Outsider  2018                         https://www.the-numbers.com/movie/Outsider-The-(2018)                3053.0                NaN              NaN            NaN
     9558      The Outsider  2018          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)                   NaN                NaN              NaN            NaN
    10265            Thirst  2009                                      https://www.the-numbers.com/movie/Thirst            13468951.0                NaN          55889.0            4.0
    10265            Thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009)            13158962.0                NaN              NaN            NaN
    10706               Val  2021                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)                   NaN                NaN              NaN            NaN
    10706               Val  2021                      https://www.the-numbers.com/movie/Val-(2021-Documentary)                   NaN                NaN              NaN            NaN
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005)            92094360.0         10000000.0       24113565.0         2261.0
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)             1295735.0                NaN              NaN            NaN
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)              460041.0                NaN              NaN            NaN
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)             2721534.0          8000000.0           8956.0            1.0

In [143]:
worldwide_sales = main_sales[
    main_sales["worldwide_box_office"].notna()
].copy()

print("Records with worldwide box office:", len(worldwide_sales))
print("Unique movies:", worldwide_sales["movie_id"].nunique())

print("\nWorldwide Sales duplicates per movie:")
ww_counts = worldwide_sales.groupby("movie_id").size()
print(ww_counts[ww_counts > 1])

print("\nWorldwide box office summary:")
print(worldwide_sales["worldwide_box_office"].describe())

Records with worldwide box office: 4926
Unique movies: 4920

Worldwide Sales duplicates per movie:
movie_id
2626     2
2627     2
5223     2
10265    2
11065    2
11229    2
dtype: int64

Worldwide box office summary:
count    4.926000e+03
mean     8.359666e+07
std      1.813283e+08
min      1.200000e+01
25%      1.252164e+06
50%      1.692981e+07
75%      8.125991e+07
max      2.845900e+09
Name: worldwide_box_office, dtype: float64

In [144]:
duplicate_check = main_sales[
    main_sales["movie_id"].isin(
        main_sales.groupby("movie_id").size()
        .loc[lambda x: x > 1]
        .index
    )
].copy()

print(
    duplicate_check[
        [
            "movie_id",
            "title",
            "year",
            "url",
            "worldwide_box_office",
            "domestic_box_office",
            "international_box_office",
            "production_budget",
            "opening_weekend",
            "theatre_count",
            "avg run per theatre"
        ]
    ]
    .sort_values(["movie_id", "url"])
    .to_string(index=False)
)

 movie_id             title  year                                                                           url  worldwide_box_office  domestic_box_office  international_box_office  production_budget  opening_weekend  theatre_count  avg run per theatre
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2012)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
      475         Aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2013)                   NaN               2955.0                       NaN                NaN           1124.0            1.0                  2.0
     2626         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0             409363.0                  672369.0                NaN         178602.0          216.0                  2.5
     2626         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0                  NaN                  238652.0                NaN              NaN            NaN                  NaN
     2627         Dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)             1081732.0             409363.0                  672369.0                NaN         178602.0          216.0                  2.5
     2627         Dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)              238652.0                  NaN                  238652.0                NaN              NaN            NaN                  NaN
     5223              Luca  2021                                 https://www.the-numbers.com/movie/Luca-(2021)            49788012.0                  NaN                49788012.0                NaN              NaN            NaN                  NaN
     5223              Luca  2021                         https://www.the-numbers.com/movie/Luca-(2021-Romania)             1002916.0                  NaN                 1002916.0                NaN              NaN            NaN                  NaN
     7976         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
     7976         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)              164802.0             126110.0                   38692.0                NaN          26855.0           35.0                  4.1
     7977         Swan Song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
     7977         Swan Song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)              164802.0             126110.0                   38692.0                NaN          26855.0           35.0                  4.1
     9558      The Outsider  2018                         https://www.the-numbers.com/movie/Outsider-The-(2018)                3053.0                  NaN                    3053.0                NaN              NaN            NaN                  NaN
     9558      The Outsider  2018          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
    10265            Thirst  2009                                      https://www.the-numbers.com/movie/Thirst            13468951.0             318574.0                13150377.0                NaN          55889.0            4.0                  2.6
    10265            Thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009)            13158962.0                  NaN                13158962.0                NaN              NaN            NaN                  NaN
    10706               Val  2021                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
    10706               Val  2021                      https://www.the-numbers.com/movie/Val-(2021-Documentary)                   NaN                  NaN                       NaN                NaN              NaN            NaN                  NaN
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005)            92094360.0           56094360.0                36000000.0         10000000.0       24113565.0         2261.0                  4.8
    11065       White Noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)             1295735.0                  NaN                 1295735.0                NaN              NaN            NaN                  NaN
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)              460041.0                  NaN                  460041.0                NaN              NaN            NaN                  NaN
    11229 Wuthering Heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)             2721534.0             100915.0                 2620619.0          8000000.0           8956.0            1.0                  5.8

In [145]:
print(
    sales_clean[
        sales_clean["title_match"].eq("thirst")
    ][
        [
            "url",
            "year",
            "release_date",
            "worldwide_box_office",
            "domestic_box_office",
            "international_box_office",
            "production_budget",
            "opening_weekend",
            "theatre_count",
            "avg run per theatre",
            "runtime",
            "creative_type"
        ]
    ].to_string(index=False)
)

                                            url  year release_date  worldwide_box_office  domestic_box_office  international_box_office  production_budget  opening_weekend  theatre_count  avg run per theatre  runtime        creative_type
https://www.the-numbers.com/movie/Thirst-(2009)  2009   April 30th            13158962.0                  NaN                13158962.0                NaN              NaN            NaN                  NaN     91.0 Contemporary Fiction
       https://www.the-numbers.com/movie/Thirst  2009    July 31st            13468951.0             318574.0                13150377.0                NaN          55889.0            4.0                  2.6      NaN              Fantasy

In [146]:
print(
    metaclean_clean[
        metaclean_clean["title_match"].eq("thirst")
    ][
        [
            "url",
            "title",
            "year_match",
            "runtime",
            "genre",
            "creative_type" if "creative_type" in metaclean_clean.columns else "genre"
        ]
    ].to_string(index=False)
)

                                    url  title  year_match  runtime                genre                genre
https://www.metacritic.com/movie/thirst Thirst        2009    133.0 Drama,Horror,Romance Drama,Horror,Romance

In [147]:
#cleaning the duplicates
# Keep the main Sales record for each movie
sales_final = main_sales.copy()

# Remove clearly alternate/country-specific records
sales_final = sales_final[
    ~sales_final["url"].str.contains(
        r"(Canada|Brazil|Romania|UK|United-Kingdom|Slovakia|Dir-|Documentary)",
        case=False,
        na=False,
        regex=True
    )
].copy()

# For duplicate movie IDs, keep the record with the most complete Sales information
sales_final["non_null_sales_fields"] = sales_final[
    [
        "worldwide_box_office",
        "domestic_box_office",
        "international_box_office",
        "production_budget",
        "opening_weekend",
        "theatre_count",
        "avg run per theatre"
    ]
].notna().sum(axis=1)

sales_final = (
    sales_final
    .sort_values(
        ["movie_id", "non_null_sales_fields"],
        ascending=[True, False]
    )
    .drop_duplicates(subset="movie_id", keep="first")
    .drop(columns="non_null_sales_fields")
)

print("Final Sales records:", len(sales_final))
print("Unique movies:", sales_final["movie_id"].nunique())
print("Duplicate movie IDs:", sales_final["movie_id"].duplicated().sum())

Final Sales records: 7663
Unique movies: 7663
Duplicate movie IDs: 0

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_29444\630293660.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ~sales_final["url"].str.contains(

In [148]:
print("Columns:")
print(sales_final.columns.tolist())

print("\nMissing values:")
print(sales_final.isna().sum())

print("\nFinal shape:")
print(sales_final.shape)

Columns:
['url', 'title_match', 'year', 'worldwide_box_office', 'domestic_box_office', 'international_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg run per theatre', 'movie_id', 'title']

Missing values:
url                            0
title_match                    0
year                           0
worldwide_box_office        2839
domestic_box_office         1062
international_box_office    2839
production_budget           4183
opening_weekend             1322
theatre_count               1314
avg run per theatre         1316
movie_id                       0
title                          0
dtype: int64

Final shape:
(7663, 12)

<h3>Constructing Movie_Sales</h3>

In [149]:
movie_sales = sales_final[
    [
        "movie_id",
        "worldwide_box_office",
        "domestic_box_office",
        "international_box_office",
        "production_budget",
        "opening_weekend",
        "theatre_count",
        "avg run per theatre"
    ]
].copy()

movie_sales = movie_sales.rename(
    columns={
        "avg run per theatre": "avg_run_per_theatre"
    }
)

movie_sales = movie_sales.reset_index(drop=True)
movie_sales.insert(0, "sales_id", range(1, len(movie_sales) + 1))

print("Shape:", movie_sales.shape)
print("\nColumns:")
print(movie_sales.columns.tolist())

print("\nFirst 5 rows:")
print(movie_sales.head())

Shape: (7663, 9)

Columns:
['sales_id', 'movie_id', 'worldwide_box_office', 'domestic_box_office', 'international_box_office', 'production_budget', 'opening_weekend', 'theatre_count', 'avg_run_per_theatre']

First 5 rows:
   sales_id  movie_id  worldwide_box_office  domestic_box_office  \
0         1         2           108286422.0           72082999.0
1         2         4              987640.0             203654.0
2         3         5                   NaN               6388.0
3         4         9               20452.0                  NaN
4         5        10               47019.0              10983.0

   international_box_office  production_budget  opening_weekend  \
0                36203423.0         15000000.0       24727437.0
1                  783986.0                NaN          22707.0
2                       NaN                NaN           3419.0
3                   20452.0                NaN              NaN
4                   36036.0                NaN              NaN

   theatre_count  avg_run_per_theatre
0         3391.0                  4.9
1            3.0                  2.1
2           13.0                  1.5
3            NaN                  NaN
4            NaN                  NaN

In [150]:
print("Duplicate sales_id:", movie_sales["sales_id"].duplicated().sum())
print("Duplicate movie_id:", movie_sales["movie_id"].duplicated().sum())
print("Missing movie_id:", movie_sales["movie_id"].isna().sum())

print("\nMissing values:")
print(movie_sales.isna().sum())

print("\nData types:")
print(movie_sales.dtypes)

Duplicate sales_id: 0
Duplicate movie_id: 0
Missing movie_id: 0

Missing values:
sales_id                       0
movie_id                       0
worldwide_box_office        2839
domestic_box_office         1062
international_box_office    2839
production_budget           4183
opening_weekend             1322
theatre_count               1314
avg_run_per_theatre         1316
dtype: int64

Data types:
sales_id                      int64
movie_id                      int64
worldwide_box_office        float64
domestic_box_office         float64
international_box_office    float64
production_budget           float64
opening_weekend             float64
theatre_count               float64
avg_run_per_theatre         float64
dtype: object

In [151]:
# Creating the csv of movie sales
movie_sales.to_csv(
    "Movie_Sales.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Movie_Sales.csv created successfully.")

Movie_Sales.csv created successfully.

<h2>Preparing the Movie_Characteristics</h2>

In [152]:
# columns from metaclean part
movie_characteristics_meta = metaclean_clean[
    [
        "url",
        "studio",
        "rating",
        "awards",
        "metascore",
        "userscore",
        "summary",
        "RelDate"
    ]
].copy()

print("Records:", len(movie_characteristics_meta))
print("\nColumns:")
print(movie_characteristics_meta.columns.tolist())

print("\nFirst 5 rows:")
print(movie_characteristics_meta.head())

Records: 11364

Columns:
['url', 'studio', 'rating', 'awards', 'metascore', 'userscore', 'summary', 'RelDate']

First 5 rows:
                                                 url  \
0  https://www.metacritic.com/movie/!women-art-re...
1  https://www.metacritic.com/movie/10-cloverfiel...
2  https://www.metacritic.com/movie/10-items-or-less
3          https://www.metacritic.com/movie/10-years
4  https://www.metacritic.com/movie/100-bloody-acres

                     studio       rating  \
0       Hotwire Productions  | Not Rated
1        Paramount Pictures      | PG-13
2                Click Star          | R
3  Anchor Bay Entertainment          | R
4           Music Box Films  | Not Rated

                                              awards  metascore  userscore  \
0                                                NaN         70        NaN
1  #18MostDiscussedMovieof2016 , #1MostSharedMovi...         76        7.7
2                                                NaN         54        5.8
3                                                NaN         61        6.9
4                                                NaN         63        7.5

                                             summary    RelDate
0                                                NaN 2011-06-01
1  Waking up from a car accident, a young woman (... 2016-03-11
2  While researching a role as a supermarket mana... 2006-12-01
3                                                NaN 2012-09-14
4  Reg and Lindsay run an organic fertilizer busi... 2013-06-28

In [153]:
sales_characteristics = sales_clean[
    [
        "url",
        "release_date",
        "runtime",
        "creative_type"
    ]
].copy()

print("Records:", len(sales_characteristics))

print("\nMissing values:")
print(sales_characteristics.isna().sum())

print("\nFirst 5 rows:")
print(sales_characteristics.head())

Records: 30612

Missing values:
url                 0
release_date        0
runtime          6053
creative_type    3945
dtype: int64

First 5 rows:
                                                 url    release_date  runtime  \
0  https://www.the-numbers.com/movie/Bakha-Satang...     January 1st    129.0
1        https://www.the-numbers.com/movie/Antitrust    January 12th      NaN
2         https://www.the-numbers.com/movie/Santitos    January 28th    105.0
3  https://www.the-numbers.com/movie/Frank-McKlus...  2002 (Wide) by      NaN
4  https://www.the-numbers.com/movie/Walk-to-Reme...    January 25th      NaN

          creative_type
0  Contemporary Fiction
1  Contemporary Fiction
2                   NaN
3                   NaN
4  Contemporary Fiction

In [154]:
# matching Sales to Movies

sales_characteristics["title_match"] = (
    sales_clean["title"]
    .astype("string")
    .str.strip()
    .str.lower()
)

sales_characteristics["year"] = sales_clean["year"]

movie_match = movie.copy()
movie_match["title_match"] = (
    movie_match["title"]
    .astype("string")
    .str.strip()
    .str.lower()
)

sales_char_matched = sales_characteristics.merge(
    movie_match[["movie_id", "title_match", "year"]],
    on=["title_match", "year"],
    how="inner"
)

print("Matched Sales characteristic records:", len(sales_char_matched))
print("Unique movies:", sales_char_matched["movie_id"].nunique())

print("\nRecords per movie:")
print(
    sales_char_matched.groupby("movie_id")
    .size()
    .value_counts()
    .sort_index()
)

Matched Sales characteristic records: 8007
Unique movies: 7991

Records per movie:
1    7977
2      12
3       2
Name: count, dtype: int64

In [155]:
#inspecting the duplicate movie characteristics
duplicate_char_counts = sales_char_matched.groupby("movie_id").size()
duplicate_char_ids = duplicate_char_counts[duplicate_char_counts > 1].index

duplicate_characteristics = (
    sales_char_matched[
        sales_char_matched["movie_id"].isin(duplicate_char_ids)
    ]
    .sort_values(["movie_id", "url"])
)

print(
    duplicate_characteristics[
        [
            "movie_id",
            "title_match",
            "year",
            "url",
            "runtime",
            "creative_type"
        ]
    ].to_string(index=False)
)

 movie_id       title_match  year                                                                           url  runtime        creative_type
      475         aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2012)      NaN      Science Fiction
      475         aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2013)     84.0 Contemporary Fiction
     2626         dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)    118.0 Contemporary Fiction
     2626         dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)    101.0   Historical Fiction
     2626         dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)     92.0              Fantasy
     2627         dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)    118.0 Contemporary Fiction
     2627         dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)    101.0   Historical Fiction
     2627         dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)     92.0              Fantasy
     3596             greta  2019                                https://www.the-numbers.com/movie/Greta-(2019)     98.0 Contemporary Fiction
     3596             greta  2019                              https://www.the-numbers.com/movie/Greta-(Brazil)     97.0 Contemporary Fiction
     5223              luca  2021                                 https://www.the-numbers.com/movie/Luca-(2021)     95.0         Kids Fiction
     5223              luca  2021                         https://www.the-numbers.com/movie/Luca-(2021-Romania)    105.0   Historical Fiction
     7100               run  2020                                  https://www.the-numbers.com/movie/Run-(2020)      NaN Contemporary Fiction
     7100               run  2020                                    https://www.the-numbers.com/movie/Run-(UK)     78.0 Contemporary Fiction
     7976         swan song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)      NaN      Science Fiction
     7976         swan song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)    105.0 Contemporary Fiction
     7977         swan song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)      NaN      Science Fiction
     7977         swan song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)    105.0 Contemporary Fiction
     9111   the interpreter  2005                      https://www.the-numbers.com/movie/Interpreter-The-(2005)    128.0 Contemporary Fiction
     9111   the interpreter  2005           https://www.the-numbers.com/movie/Interpreter-The-(Slovakia)-(2018)    113.0 Contemporary Fiction
     9558      the outsider  2018                         https://www.the-numbers.com/movie/Outsider-The-(2018)    120.0   Historical Fiction
     9558      the outsider  2018          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)     99.0              Factual
    10265            thirst  2009                                      https://www.the-numbers.com/movie/Thirst      NaN              Fantasy
    10265            thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009)     91.0 Contemporary Fiction
    10706               val  2021                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)     81.0 Contemporary Fiction
    10706               val  2021                      https://www.the-numbers.com/movie/Val-(2021-Documentary)    109.0              Factual
    11065       white noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005)    101.0 Contemporary Fiction
    11065       white noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)     94.0              Factual
    11229 wuthering heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)    142.0   Historical Fiction
    11229 wuthering heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)    128.0   Historical Fiction

In [156]:
duplicate_ids = duplicate_char_counts[duplicate_char_counts > 1].index

meta_duplicate_check = metaclean_clean[
    metaclean_clean["title_match"].isin(
        movie_match[movie_match["movie_id"].isin(duplicate_ids)]["title_match"]
    )
][
    [
        "url",
        "title",
        "year_match",
        "runtime",
        "genre"
    ]
]

print(meta_duplicate_check.to_string(index=False))

                                               url             title  year_match  runtime                                     genre
        https://www.metacritic.com/movie/aftermath         Aftermath        2013    107.0                            Drama,Thriller
   https://www.metacritic.com/movie/aftermath-2014         Aftermath        2014     92.0                           Action,Thriller
   https://www.metacritic.com/movie/aftermath-2017         Aftermath        2017     94.0                            Drama,Thriller
   https://www.metacritic.com/movie/dreamland-2019         Dreamland        2020     98.0                            Drama,Thriller
   https://www.metacritic.com/movie/dreamland-2020         Dreamland        2020     92.0               Fantasy,Horror,Comedy,Crime
            https://www.metacritic.com/movie/greta             Greta        2019     98.0             Drama,Mystery,Thriller,Horror
             https://www.metacritic.com/movie/luca              Luca        2021     95.0 Adventure,Fantasy,Comedy,Animation,Family
              https://www.metacritic.com/movie/run               Run        2020     90.0                   Mystery,Thriller,Horror
        https://www.metacritic.com/movie/swan-song         Swan Song        2021    105.0                                     Drama
   https://www.metacritic.com/movie/swan-song-2021         Swan Song        2021    116.0                              Sci-Fi,Drama
  https://www.metacritic.com/movie/the-interpreter   The Interpreter        2005    128.0                    Drama,Mystery,Thriller
     https://www.metacritic.com/movie/the-outsider      The Outsider        2006     85.0                               Documentary
https://www.metacritic.com/movie/the-outsider-2014      The Outsider        2014     94.0       Action,Drama,Mystery,Thriller,Crime
https://www.metacritic.com/movie/the-outsider-2018      The Outsider        2018    120.0              Drama,Mystery,Thriller,Crime
           https://www.metacritic.com/movie/thirst            Thirst        2009    133.0                      Drama,Horror,Romance
              https://www.metacritic.com/movie/val               Val        2021    109.0                               Documentary
      https://www.metacritic.com/movie/white-noise       White Noise        2005    101.0      Sci-Fi,Drama,Mystery,Thriller,Horror
https://www.metacritic.com/movie/wuthering-heights Wuthering Heights        2012    129.0                             Drama,Romance

In [157]:
# checking if creative_types can be matched correctly
creative_check = sales_char_matched[
    sales_char_matched["creative_type"].notna()
].copy()

print("Movies with creative_type:", creative_check["movie_id"].nunique())

print("\nCreative type values:")
print(creative_check["creative_type"].value_counts())

print("\nMissing creative_type:", sales_char_matched["creative_type"].isna().sum())

Movies with creative_type: 7335

Creative type values:
creative_type
Contemporary Fiction       3713
Factual                    1297
Historical Fiction          632
Dramatization               612
Science Fiction             413
Fantasy                     328
Kids Fiction                262
Super Hero                   90
Multiple Creative Types       4
Name: count, dtype: int64

Missing creative_type: 656

In [158]:
creative_conflicts = (
    sales_char_matched
    .dropna(subset=["creative_type"])
    .groupby("movie_id")["creative_type"]
    .nunique()
)

creative_conflicts = creative_conflicts[creative_conflicts > 1]

print("Movies with conflicting creative types:", len(creative_conflicts))

if len(creative_conflicts) > 0:
    print("\nConflicting movies:")
    print(
        sales_char_matched[
            sales_char_matched["movie_id"].isin(creative_conflicts.index)
        ][
            ["movie_id", "title_match", "year", "url", "creative_type"]
        ]
        .sort_values(["movie_id", "url"])
        .to_string(index=False)
    )

Movies with conflicting creative types: 10

Conflicting movies:
 movie_id  title_match  year                                                                           url        creative_type
      475    aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2012)      Science Fiction
      475    aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2013) Contemporary Fiction
     2626    dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020) Contemporary Fiction
     2626    dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)   Historical Fiction
     2626    dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)              Fantasy
     2627    dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020) Contemporary Fiction
     2627    dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)   Historical Fiction
     2627    dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)              Fantasy
     5223         luca  2021                                 https://www.the-numbers.com/movie/Luca-(2021)         Kids Fiction
     5223         luca  2021                         https://www.the-numbers.com/movie/Luca-(2021-Romania)   Historical Fiction
     7976    swan song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)      Science Fiction
     7976    swan song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens) Contemporary Fiction
     7977    swan song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)      Science Fiction
     7977    swan song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens) Contemporary Fiction
     9558 the outsider  2018                         https://www.the-numbers.com/movie/Outsider-The-(2018)   Historical Fiction
     9558 the outsider  2018          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)              Factual
    10265       thirst  2009                                      https://www.the-numbers.com/movie/Thirst              Fantasy
    10265       thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009) Contemporary Fiction
    10706          val  2021                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin) Contemporary Fiction
    10706          val  2021                      https://www.the-numbers.com/movie/Val-(2021-Documentary)              Factual
    11065  white noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005) Contemporary Fiction
    11065  white noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)              Factual

In [159]:
conflict_ids = creative_conflicts.index

conflict_rows = sales_char_matched[
    sales_char_matched["movie_id"].isin(conflict_ids)
].copy()

print(
    conflict_rows[
        [
            "movie_id",
            "title_match",
            "year",
            "url",
            "runtime",
            "creative_type"
        ]
    ]
    .sort_values(["movie_id", "url"])
    .to_string(index=False)
)

 movie_id  title_match  year                                                                           url  runtime        creative_type
      475    aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2012)      NaN      Science Fiction
      475    aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2013)     84.0 Contemporary Fiction
     2626    dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)    118.0 Contemporary Fiction
     2626    dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)    101.0   Historical Fiction
     2626    dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)     92.0              Fantasy
     2627    dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)    118.0 Contemporary Fiction
     2627    dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)    101.0   Historical Fiction
     2627    dreamland  2020                          https://www.the-numbers.com/movie/Dreamland-(Canada)     92.0              Fantasy
     5223         luca  2021                                 https://www.the-numbers.com/movie/Luca-(2021)     95.0         Kids Fiction
     5223         luca  2021                         https://www.the-numbers.com/movie/Luca-(2021-Romania)    105.0   Historical Fiction
     7976    swan song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)      NaN      Science Fiction
     7976    swan song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)    105.0 Contemporary Fiction
     7977    swan song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)      NaN      Science Fiction
     7977    swan song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)    105.0 Contemporary Fiction
     9558 the outsider  2018                         https://www.the-numbers.com/movie/Outsider-The-(2018)    120.0   Historical Fiction
     9558 the outsider  2018          https://www.the-numbers.com/movie/Outsider-The-(2018-United-Kingdom)     99.0              Factual
    10265       thirst  2009                                      https://www.the-numbers.com/movie/Thirst      NaN              Fantasy
    10265       thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009)     91.0 Contemporary Fiction
    10706          val  2021                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)     81.0 Contemporary Fiction
    10706          val  2021                      https://www.the-numbers.com/movie/Val-(2021-Documentary)    109.0              Factual
    11065  white noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005)    101.0 Contemporary Fiction
    11065  white noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)     94.0              Factual

In [160]:
# Remove country-specific Sales records
sales_char_clean = sales_char_matched[
    ~sales_char_matched["url"].str.contains(
        r"Canada|Brazil|Romania|UK|United-Kingdom|Slovakia",
        case=False,
        na=False,
        regex=True
    )
].copy()

# Extract URL type to identify main movie entries
sales_char_clean["url_type"] = sales_char_clean["url"].str.extract(
    r"\(([^()]*)\)"
)[0]

print("Records after removing country-specific records:", len(sales_char_clean))

print("\nRecords per movie:")
print(
    sales_char_clean.groupby("movie_id")
    .size()
    .value_counts()
    .sort_index()
)

print("\nRemaining duplicate movie IDs:")
remaining = sales_char_clean.groupby("movie_id").size()
print(remaining[remaining > 1])

Records after removing country-specific records: 7779

Records per movie:
1    7761
2       9
Name: count, dtype: int64

Remaining duplicate movie IDs:
movie_id
475      2
2626     2
2627     2
7976     2
7977     2
10265    2
10706    2
11065    2
11229    2
dtype: int64

In [161]:
remaining_duplicate_ids = (
    sales_char_clean.groupby("movie_id")
    .size()
    .loc[lambda x: x > 1]
    .index
)

print(
    sales_char_clean[
        sales_char_clean["movie_id"].isin(remaining_duplicate_ids)
    ][
        [
            "movie_id",
            "title_match",
            "year",
            "url",
            "runtime",
            "creative_type"
        ]
    ]
    .sort_values(["movie_id", "url"])
    .to_string(index=False)
)

 movie_id       title_match  year                                                                           url  runtime        creative_type
      475         aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2012)      NaN      Science Fiction
      475         aftermath  2014                            https://www.the-numbers.com/movie/Aftermath-(2013)     84.0 Contemporary Fiction
     2626         dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)    118.0 Contemporary Fiction
     2626         dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)    101.0   Historical Fiction
     2627         dreamland  2020                            https://www.the-numbers.com/movie/Dreamland-(2020)    118.0 Contemporary Fiction
     2627         dreamland  2020 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)    101.0   Historical Fiction
     7976         swan song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)      NaN      Science Fiction
     7976         swan song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)    105.0 Contemporary Fiction
     7977         swan song  2021                            https://www.the-numbers.com/movie/Swan-Song-(2021)      NaN      Science Fiction
     7977         swan song  2021          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)    105.0 Contemporary Fiction
    10265            thirst  2009                                      https://www.the-numbers.com/movie/Thirst      NaN              Fantasy
    10265            thirst  2009                               https://www.the-numbers.com/movie/Thirst-(2009)     91.0 Contemporary Fiction
    10706               val  2021                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)     81.0 Contemporary Fiction
    10706               val  2021                      https://www.the-numbers.com/movie/Val-(2021-Documentary)    109.0              Factual
    11065       white noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2005)    101.0 Contemporary Fiction
    11065       white noise  2005                          https://www.the-numbers.com/movie/White-Noise-(2020)     94.0              Factual
    11229 wuthering heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)    142.0   Historical Fiction
    11229 wuthering heights  2012                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)    128.0   Historical Fiction

In [162]:
# chekcing which movie represents metaclean id s
check_ids = [475, 2626, 2627, 7976, 7977, 10265, 10706, 11065, 11229]

print(
    movie[
        movie["movie_id"].isin(check_ids)
    ][
        ["movie_id", "title", "year", "url"]
    ]
    .sort_values("movie_id")
    .to_string(index=False)
)

print("\n--- MetaClean matching records ---")

print(
    metaclean_clean[
        metaclean_clean["title_match"].isin(
            sales_char_clean[
                sales_char_clean["movie_id"].isin(check_ids)
            ]["title_match"].unique()
        )
    ][
        [
            "url",
            "title",
            "RelDate",
            "runtime",
            "genre",
            "studio"
        ]
    ]
    .sort_values(["title", "RelDate"])
    .to_string(index=False)
)

 movie_id             title  year                                                url
      475         Aftermath  2014    https://www.metacritic.com/movie/aftermath-2014
     2626         Dreamland  2020    https://www.metacritic.com/movie/dreamland-2019
     2627         Dreamland  2020    https://www.metacritic.com/movie/dreamland-2020
     7976         Swan Song  2021         https://www.metacritic.com/movie/swan-song
     7977         Swan Song  2021    https://www.metacritic.com/movie/swan-song-2021
    10265            Thirst  2009            https://www.metacritic.com/movie/thirst
    10706               Val  2021               https://www.metacritic.com/movie/val
    11065       White Noise  2005       https://www.metacritic.com/movie/white-noise
    11229 Wuthering Heights  2012 https://www.metacritic.com/movie/wuthering-heights

--- MetaClean matching records ---
                                               url             title    RelDate  runtime                                genre                 studio
        https://www.metacritic.com/movie/aftermath         Aftermath 2013-11-01    107.0                       Drama,Thriller         Menemsha Films
   https://www.metacritic.com/movie/aftermath-2014         Aftermath 2014-07-18     92.0                      Action,Thriller    Image Entertainment
   https://www.metacritic.com/movie/aftermath-2017         Aftermath 2017-04-07     94.0                       Drama,Thriller     Lionsgate Premiere
   https://www.metacritic.com/movie/dreamland-2020         Dreamland 2020-06-05     92.0          Fantasy,Horror,Comedy,Crime Uncork'd Entertainment
   https://www.metacritic.com/movie/dreamland-2019         Dreamland 2020-11-13     98.0                       Drama,Thriller     Paramount Pictures
        https://www.metacritic.com/movie/swan-song         Swan Song 2021-08-06    105.0                                Drama      Magnolia Pictures
   https://www.metacritic.com/movie/swan-song-2021         Swan Song 2021-12-17    116.0                         Sci-Fi,Drama              Apple TV+
           https://www.metacritic.com/movie/thirst            Thirst 2009-07-31    133.0                 Drama,Horror,Romance         Focus Features
              https://www.metacritic.com/movie/val               Val 2021-07-23    109.0                          Documentary         Amazon Studios
      https://www.metacritic.com/movie/white-noise       White Noise 2005-01-07    101.0 Sci-Fi,Drama,Mystery,Thriller,Horror     Universal Pictures
https://www.metacritic.com/movie/wuthering-heights Wuthering Heights 2012-10-05    129.0                        Drama,Romance  Oscilloscope Pictures

In [163]:
id_check = movie[movie["movie_id"].isin(check_ids)][
    ["movie_id", "title", "year", "url"]
].copy()

id_check["metaclean_url"] = id_check["url"].str.lower()

comparison = sales_char_clean[
    sales_char_clean["movie_id"].isin(check_ids)
][
    ["movie_id", "url", "runtime", "creative_type"]
].copy()

comparison = comparison.merge(
    id_check[["movie_id", "metaclean_url"]],
    on="movie_id",
    how="left"
)

print(comparison.to_string(index=False))

 movie_id                                                                           url  runtime        creative_type                                      metaclean_url
      475                            https://www.the-numbers.com/movie/Aftermath-(2013)     84.0 Contemporary Fiction    https://www.metacritic.com/movie/aftermath-2014
    11229                    https://www.the-numbers.com/movie/Wuthering-Heights-(2011)    128.0   Historical Fiction https://www.metacritic.com/movie/wuthering-heights
      475                            https://www.the-numbers.com/movie/Aftermath-(2012)      NaN      Science Fiction    https://www.metacritic.com/movie/aftermath-2014
    11229                    https://www.the-numbers.com/movie/Wuthering-Heights-(2009)    142.0   Historical Fiction https://www.metacritic.com/movie/wuthering-heights
    10265                               https://www.the-numbers.com/movie/Thirst-(2009)     91.0 Contemporary Fiction            https://www.metacritic.com/movie/thirst
    10265                                      https://www.the-numbers.com/movie/Thirst      NaN              Fantasy            https://www.metacritic.com/movie/thirst
    11065                          https://www.the-numbers.com/movie/White-Noise-(2020)     94.0              Factual       https://www.metacritic.com/movie/white-noise
    11065                          https://www.the-numbers.com/movie/White-Noise-(2005)    101.0 Contemporary Fiction       https://www.metacritic.com/movie/white-noise
     2626                            https://www.the-numbers.com/movie/Dreamland-(2020)    118.0 Contemporary Fiction    https://www.metacritic.com/movie/dreamland-2019
     2627                            https://www.the-numbers.com/movie/Dreamland-(2020)    118.0 Contemporary Fiction    https://www.metacritic.com/movie/dreamland-2020
     2626 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)    101.0   Historical Fiction    https://www.metacritic.com/movie/dreamland-2019
     2627 https://www.the-numbers.com/movie/Dreamland-(2020-Dir-Miles-Joris-Peyrafitte)    101.0   Historical Fiction    https://www.metacritic.com/movie/dreamland-2020
     7976                            https://www.the-numbers.com/movie/Swan-Song-(2021)      NaN      Science Fiction         https://www.metacritic.com/movie/swan-song
     7977                            https://www.the-numbers.com/movie/Swan-Song-(2021)      NaN      Science Fiction    https://www.metacritic.com/movie/swan-song-2021
    10706                https://www.the-numbers.com/movie/Val-(2021-Dir-Aaron-Fradkin)     81.0 Contemporary Fiction               https://www.metacritic.com/movie/val
     7976          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)    105.0 Contemporary Fiction         https://www.metacritic.com/movie/swan-song
     7977          https://www.the-numbers.com/movie/Swan-Song-(2021-Dir-Todd-Stephens)    105.0 Contemporary Fiction    https://www.metacritic.com/movie/swan-song-2021
    10706                      https://www.the-numbers.com/movie/Val-(2021-Documentary)    109.0              Factual               https://www.metacritic.com/movie/val

In [164]:
sales_char_final = sales_char_clean.copy()

print("Records:", len(sales_char_final))
print("Unique movies:", sales_char_final["movie_id"].nunique())

print("\nRecords per movie:")
print(
    sales_char_final.groupby("movie_id")
    .size()
    .value_counts()
    .sort_index()
)

Records: 7779
Unique movies: 7770

Records per movie:
1    7761
2       9
Name: count, dtype: int64

In [165]:
#Combining the sources to form the table
movie_characters = sales_char_final.merge(
    movie_characteristics_meta,
    on="url",
    how="left"
)

print("Records:", len(movie_characters))
print("Unique movies:", movie_characters["movie_id"].nunique())

print("\nColumns:")
print(movie_characters.columns.tolist())

Records: 7779
Unique movies: 7770

Columns:
['url', 'release_date', 'runtime', 'creative_type', 'title_match', 'year', 'movie_id', 'url_type', 'studio', 'rating', 'awards', 'metascore', 'userscore', 'summary', 'RelDate']

<h3>Creating the Movie_characteristics table</h3>

In [166]:
movie_characters = movie_characters[
    [
        "movie_id",
        "url",
        "RelDate",
        "studio",
        "rating",
        "runtime",
        "creative_type",
        "awards",
        "metascore",
        "userscore",
        "summary"
    ]
].copy()

movie_characters = movie_characters.rename(
    columns={"RelDate": "release_date"}
)

print(movie_characters.columns.tolist())
print("\nRecords:", len(movie_characters))
print("Unique movies:", movie_characters["movie_id"].nunique())

['movie_id', 'url', 'release_date', 'studio', 'rating', 'runtime', 'creative_type', 'awards', 'metascore', 'userscore', 'summary']

Records: 7779
Unique movies: 7770

In [167]:
# check
print("Missing values:")
print(movie_characters.isna().sum())

print("\nData types:")
print(movie_characters.dtypes)

Missing values:
movie_id            0
url                 0
release_date     7779
studio           7779
rating           7779
runtime          1607
creative_type     650
awards           7779
metascore        7779
userscore        7779
summary          7779
dtype: int64

Data types:
movie_id                  int64
url                         str
release_date     datetime64[us]
studio                      str
rating                      str
runtime                 float64
creative_type               str
awards                      str
metascore               float64
userscore               float64
summary                     str
dtype: object

In [168]:
# Prepare MetaClean for matching
meta_match = metaclean_clean.copy()

meta_match["title_match"] = (
    meta_match["title"]
    .astype("string")
    .str.strip()
    .str.lower()
)

meta_match["year"] = meta_match["RelDate"].dt.year

# Keep only the MetaClean columns we need
meta_match = meta_match[
    [
        "title_match",
        "year",
        "studio",
        "rating",
        "runtime",
        "awards",
        "metascore",
        "userscore",
        "summary",
        "RelDate"
    ]
].copy()

print("MetaClean records:", len(meta_match))
print("Duplicate title/year combinations:")
print(
    meta_match.groupby(["title_match", "year"])
    .size()
    .loc[lambda x: x > 1]
)

MetaClean records: 11364
Duplicate title/year combinations:
title_match  year
dreamland    2020    2
swan song    2021    2
the hunter   2012    2
dtype: int64

In [169]:
meta_match = metaclean_clean[
    [
        "url",
        "title",
        "RelDate",
        "studio",
        "rating",
        "runtime",
        "awards",
        "metascore",
        "userscore",
        "summary"
    ]
].copy()

meta_match = meta_match.rename(columns={
    "url": "metaclean_url"
})

movie_meta = movie[
    ["movie_id", "url"]
].copy()

movie_meta = movie_meta.rename(columns={
    "url": "metaclean_url"
})

movie_meta = movie_meta.merge(
    meta_match,
    on="metaclean_url",
    how="left"
)

print("Records:", len(movie_meta))
print("Unique movies:", movie_meta["movie_id"].nunique())
print("\nMissing MetaClean matches:")
print(movie_meta.isna().sum())

Records: 11364
Unique movies: 11364

Missing MetaClean matches:
movie_id            0
metaclean_url       0
title               0
RelDate             0
studio            350
rating           1067
runtime           255
awards           6977
metascore           0
userscore        2105
summary          5897
dtype: int64

In [170]:
movie_characteristics = sales_char_final.merge(
    movie_meta[
        [
            "movie_id",
            "studio",
            "rating",
            "runtime",
            "awards",
            "metascore",
            "userscore",
            "summary",
            "RelDate"
        ]
    ],
    on="movie_id",
    how="left",
    suffixes=("_sales", "_meta")
)

print("Records:", len(movie_characteristics))
print("Unique movies:", movie_characteristics["movie_id"].nunique())

print("\nColumns:")
print(movie_characteristics.columns.tolist())

Records: 7779
Unique movies: 7770

Columns:
['url', 'release_date', 'runtime_sales', 'creative_type', 'title_match', 'year', 'movie_id', 'url_type', 'studio', 'rating', 'runtime_meta', 'awards', 'metascore', 'userscore', 'summary', 'RelDate']

In [171]:
# comparing by runtime
runtime_check = movie_characteristics[
    ["movie_id", "runtime_sales", "runtime_meta"]
].copy()

runtime_check["difference"] = (
    runtime_check["runtime_sales"] - runtime_check["runtime_meta"]
).abs()

print("Both runtimes available:",
      runtime_check[["runtime_sales", "runtime_meta"]].notna().all(axis=1).sum())

print("Sales runtime missing:",
      runtime_check["runtime_sales"].isna().sum())

print("MetaClean runtime missing:",
      runtime_check["runtime_meta"].isna().sum())

print("\nRuntime difference:")
print(runtime_check["difference"].describe())

Both runtimes available: 6057
Sales runtime missing: 1607
MetaClean runtime missing: 161

Runtime difference:
count    6057.000000
mean        1.620769
std         5.094158
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max       202.000000
Name: difference, dtype: float64

In [172]:
#in case of runtime is missing, it will take from the other source
movie_characteristics["runtime"] = (
    movie_characteristics["runtime_meta"]
    .fillna(movie_characteristics["runtime_sales"])
)

print("Missing runtime:", movie_characteristics["runtime"].isna().sum())

print("\nRuntime statistics:")
print(movie_characteristics["runtime"].describe())

Missing runtime: 46

Runtime statistics:
count    7733.000000
mean      102.152981
std        18.724533
min        21.000000
25%        91.000000
50%        99.000000
75%       110.000000
max       808.000000
Name: runtime, dtype: float64

In [173]:
#inspecting unusual runtimes
print(
    movie_characteristics[
        movie_characteristics["runtime"] > 300
    ][
        [
            "movie_id",
            "url",
            "runtime_sales",
            "runtime_meta",
            "runtime"
        ]
    ]
    .sort_values("runtime", ascending=False)
    .to_string(index=False)
)

 movie_id                                                          url  runtime_sales  runtime_meta  runtime
     4797 https://www.the-numbers.com/movie/Flor-La-(Argentina)-(2018)          803.0         808.0    808.0
     1720                     https://www.the-numbers.com/movie/Carlos          123.0         325.0    325.0

In [174]:
print(
    movie_characteristics[
        movie_characteristics["movie_id"].isin([4797, 1720])
    ][
        [
            "movie_id",
            "url",
            "runtime_sales",
            "runtime_meta",
            "runtime"
        ]
    ].to_string(index=False)
)

 movie_id                                                          url  runtime_sales  runtime_meta  runtime
     1720                     https://www.the-numbers.com/movie/Carlos          123.0         325.0    325.0
     4797 https://www.the-numbers.com/movie/Flor-La-(Argentina)-(2018)          803.0         808.0    808.0

In [175]:
print("Missing creative_type:",
      movie_characteristics["creative_type"].isna().sum())

print("\nCreative type values:")
print(
    movie_characteristics["creative_type"]
    .value_counts(dropna=False)
)

Missing creative_type: 650

Creative type values:
creative_type
Contemporary Fiction       3611
Factual                    1257
NaN                         650
Historical Fiction          606
Dramatization               578
Science Fiction             402
Fantasy                     325
Kids Fiction                256
Super Hero                   90
Multiple Creative Types       4
Name: count, dtype: int64

In [176]:
print("Missing rating:",
      movie_characteristics["rating"].isna().sum())

print("\nRating values:")
print(
    movie_characteristics["rating"]
    .value_counts(dropna=False)
)

Missing rating: 566

Rating values:
rating
| R            2773
| PG-13        1690
| Not Rated    1506
| PG            644
NaN             566
| Unrated       244
| TV-MA          98
| G              93
| NR             78
| NC-17          31
| TV-14          27
| TV-PG          12
| TV-G            5
| PG--13          4
| Open            4
| Approved        2
| MA-17           1
| M/PG            1
Name: count, dtype: int64

In [177]:
# cleaning rating
movie_characteristics["rating"] = (
    movie_characteristics["rating"]
    .str.replace("|", "", regex=False)
    .str.strip()
    .replace({
        "PG--13": "PG-13",
        "Unrated": "Not Rated",
        "NR": "Not Rated"
    })
)

print("Missing rating:",
      movie_characteristics["rating"].isna().sum())

print("\nCleaned rating values:")
print(
    movie_characteristics["rating"]
    .value_counts(dropna=False)
)

Missing rating: 566

Cleaned rating values:
rating
R            2773
Not Rated    1828
PG-13        1694
PG            644
NaN           566
TV-MA          98
G              93
NC-17          31
TV-14          27
TV-PG          12
TV-G            5
Open            4
Approved        2
MA-17           1
M/PG            1
Name: count, dtype: int64

In [178]:
print("Missing awards:",
      movie_characteristics["awards"].isna().sum())

print("\nNumber of unique awards values:",
      movie_characteristics["awards"].nunique())

print("\nSample awards values:")
print(
    movie_characteristics["awards"]
    .dropna()
    .head(30)
    .to_string(index=False)
)

# so awards should stay as text field

Missing awards: 4629

Number of unique awards values: 3149

Sample awards values:
                       #68MostDiscussedMovieof2001
#28MostDiscussedMovieof2002 , #10MostSharedMovi...
                          #84MostSharedMovieof2008
                                #44BestMovieof2011
#31MostDiscussedMovieof2011 , #76MostSharedMovi...
                       #72MostDiscussedMovieof2011
#85MostDiscussedMovieof2011 , #46MostSharedMovi...
                       #83MostDiscussedMovieof2011
                                #90BestMovieof2015
                                #86BestMovieof2015
                          #60MostSharedMovieof2015
#6MostDiscussedMovieof2015 , #4MostSharedMovieo...
                       #41MostDiscussedMovieof2018
                       #89MostDiscussedMovieof2018
                       #40MostDiscussedMovieof2018
#8BestMovieof2017 , #49MostDiscussedMovieof2017...
#83MostDiscussedMovieof2017 , #92MostSharedMovi...
                       #71MostDiscussedMovieof2018
                                #29BestMovieof2018
#50BestMovieof2017 , #48MostDiscussedMovieof201...
#69MostDiscussedMovieof2017 , #88MostSharedMovi...
                       #22MostDiscussedMovieof2018
                       #25MostDiscussedMovieof2018
#1BestMovieof2018 , #24MostDiscussedMovieof2018...
#63MostDiscussedMovieof2017 , #73MostSharedMovi...
                       #97MostDiscussedMovieof2017
#33MostDiscussedMovieof2017 , #37MostSharedMovi...
#12MostDiscussedMovieof2017 , #58MostSharedMovi...
#27MostDiscussedMovieof2017 , #50MostSharedMovi...
#6MostDiscussedMovieof2018 , #64MostSharedMovie...

In [179]:
print("Missing metascore:",
      movie_characteristics["metascore"].isna().sum())

print("\nMetascore statistics:")
print(movie_characteristics["metascore"].describe())

print("\nUnique metascore values:",
      movie_characteristics["metascore"].nunique())

Missing metascore: 0

Metascore statistics:
count    7779.000000
mean       56.331534
std        17.078954
min         1.000000
25%        44.000000
50%        57.000000
75%        69.000000
max       100.000000
Name: metascore, dtype: float64

Unique metascore values: 96

In [180]:
print("Missing userscore:",
      movie_characteristics["userscore"].isna().sum())

print("\nUserscore statistics:")
print(movie_characteristics["userscore"].describe())

print("\nUnique userscore values:",
      movie_characteristics["userscore"].nunique())

Missing userscore: 1205

Userscore statistics:
count    6574.000000
mean        6.515546
std         1.383391
min         0.600000
25%         5.700000
50%         6.700000
75%         7.500000
max         9.700000
Name: userscore, dtype: float64

Unique userscore values: 86

In [181]:
print("Missing summary:",
      movie_characteristics["summary"].isna().sum())

print("\nNumber of unique summaries:",
      movie_characteristics["summary"].nunique())

print("\nSample summaries:")
print(
    movie_characteristics["summary"]
    .dropna()
    .head(10)
    .to_string(index=False)
)

Missing summary: 3976

Number of unique summaries: 3801

Sample summaries:
A relentless suspense thriller that enters the ...
Alejandro Springall directs this Spanish-langua...
Set in the lowlands of North Carolina, this sto...
The Darkest Hour is the story of five young peo...
Three elite climbers struggle to find their way...
A determined dog comes to the rescue and helps ...
Vice explores the epic story about how a bureau...
A humorous take on Arthur Conan Doyle's classic...
Kyle and Peter Reynolds (Owen Wilson and Ed Hel...
On the run in the year 1987, Bumblebee finds re...

In [182]:
print("Missing studio:",
      movie_characteristics["studio"].isna().sum())

print("\nNumber of unique studios:",
      movie_characteristics["studio"].nunique())

print("\nSample studio values:")
print(
    movie_characteristics["studio"]
    .dropna()
    .value_counts()
    .head(20)
)

Missing studio: 188

Number of unique studios: 811

Sample studio values:
studio
Universal Pictures                        306
IFC Films                                 275
Warner Bros. Pictures                     274
Paramount Pictures                        239
Twentieth Century Fox Film Corporation    235
Columbia Pictures                         225
Sony Pictures Classics                    216
Lionsgate                                 204
Magnolia Pictures                         183
Fox Searchlight Pictures                  139
Walt Disney Studios Motion Pictures       127
Focus Features                            121
Buena Vista Pictures                      109
Miramax Films                             108
New Line Cinema                           105
Lions Gate Films                           95
Warner Bros.                               90
Strand Releasing                           90
First Run Features                         89
Roadside Attractions                       89
Name: count, dtype: int64

In [183]:
# suiting the table to the ERD
movie_characteristics_final = movie_characteristics[
    [
        "movie_id",
        "url",
        "RelDate",
        "studio",
        "rating",
        "runtime",
        "creative_type",
        "awards",
        "metascore",
        "userscore",
        "summary"
    ]
].copy()

movie_characteristics_final = movie_characteristics_final.rename(
    columns={"RelDate": "release_date"}
)

movie_characteristics_final.insert(
    0,
    "movie_characteristics_id",
    range(1, len(movie_characteristics_final) + 1)
)

print("Shape:", movie_characteristics_final.shape)
print("\nColumns:")
print(movie_characteristics_final.columns.tolist())

print("\nDuplicate characteristics IDs:",
      movie_characteristics_final["movie_characteristics_id"].duplicated().sum())

print("\nMissing values:")
print(movie_characteristics_final.isna().sum())

Shape: (7779, 12)

Columns:
['movie_characteristics_id', 'movie_id', 'url', 'release_date', 'studio', 'rating', 'runtime', 'creative_type', 'awards', 'metascore', 'userscore', 'summary']

Duplicate characteristics IDs: 0

Missing values:
movie_characteristics_id       0
movie_id                       0
url                            0
release_date                   0
studio                       188
rating                       566
runtime                       46
creative_type                650
awards                      4629
metascore                      0
userscore                   1205
summary                     3976
dtype: int64

<h4>Exporting the Movie_Characteristics table</h4>

In [184]:
movie_characteristics_final.to_csv(
    "Movie_Characteristics.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Movie_Characteristics.csv created successfully.")

Movie_Characteristics.csv created successfully.

<h3>Preparing Genre table</h3>

In [185]:
print("Missing genres:",
      sales_clean["genre"].isna().sum())

print("\nNumber of unique genres:",
      sales_clean["genre"].nunique())

print("\nGenre values:")
print(
    sales_clean["genre"]
    .value_counts(dropna=False)
)

Missing genres: 1704

Number of unique genres: 15

Genre values:
genre
Drama                  9218
Documentary            4683
Comedy                 4551
Thriller/Suspense      2281
Adventure              1999
Action                 1872
NaN                    1704
Horror                 1630
Romantic Comedy        1177
Concert/Performance     711
Musical                 268
Black Comedy            245
Multiple Genres         159
Western                 105
Educational               5
Reality                   4
Name: count, dtype: int64

In [186]:
# checking the movies that are marked as multiple genres
multiple_genres = sales_clean[
    sales_clean["genre"] == "Multiple Genres"
][
    ["title", "year", "genre", "url"]
].copy()

print("Movies marked Multiple Genres:", len(multiple_genres))

print("\nExamples:")
print(
    multiple_genres.head(20).to_string(index=False)
)

Movies marked Multiple Genres: 159

Examples:
                                   title  year           genre                                                                            url
             La Higuera de los bastardos  2017 Multiple Genres   https://www.the-numbers.com/movie/Higuera-de-los-bastardos-La-(Spain)-(2017)
                   Indian films screened  2018 Multiple Genres                 https://www.the-numbers.com/movie/Indian-films-screened-(2018)
   Beijing international film festival 1  2018 Multiple Genres https://www.the-numbers.com/movie/Beijing-international-film-festival-1-(2018)
                               Taxiwaala  2018 Multiple Genres                      https://www.the-numbers.com/movie/Taxiwaala-(India)(2018)
JUNGLEBOOK & PETER PAN Christmas special  2017 Multiple Genres   https://www.the-numbers.com/movie/JUNGLEBOOK-and-PETER-PAN-Christmas-special
                 Ten, kdo tÃ„â€º miloval  2018 Multiple Genres                https://www.the-numbers.com/movie/Ten-kdo-te-miloval-(CZ)(2018)
                   LittleScreen December  2016 Multiple Genres                   https://www.the-numbers.com/movie/LittleScreen-December-(UK)
                                    DOGG  2017 Multiple Genres                              https://www.the-numbers.com/movie/DOGG-(Slovakia)
Videofilia: y otros sÃƒÂ­ndromes virales  2016 Multiple Genres  https://www.the-numbers.com/movie/Videofilia-y-otros-sindromes-virales-(Peru)
  The Heyday of the Insensitive Bastards  2017 Multiple Genres       https://www.the-numbers.com/movie/Heyday-of-the-Insensitive-Bastards-The
          The Toxic Avenger: The Musical  2018 Multiple Genres                https://www.the-numbers.com/movie/Toxic-Avenger-The-Musical-The
                 Como una novia sin sexo  2016 Multiple Genres   https://www.the-numbers.com/movie/Como-una-novia-sin-sexo-(Argentina)-(2016)
                Strangeways Here We Come  2018 Multiple Genres          https://www.the-numbers.com/movie/Strangeways-Here-We-Come-(UK)(2018)
                     Female Human Animal  2018 Multiple Genres               https://www.the-numbers.com/movie/Female-Human-Animal-(UK)(2018)
                               The Stray  2017 Multiple Genres                             https://www.the-numbers.com/movie/Stray-The-(2017)
                               Andhadhun  2018 Multiple Genres                      https://www.the-numbers.com/movie/Andhadhun-(India)(2018)
                   Little Screen October  2016 Multiple Genres                   https://www.the-numbers.com/movie/Little-Screen-October-(UK)
                          Menudos heroes  2015 Multiple Genres                  https://www.the-numbers.com/movie/Menudos-heroes-(2021-Spain)
                               Size Zero  2015 Multiple Genres                            https://www.the-numbers.com/movie/Size-Zero-(India)
                                  Mulgoe  2018 Multiple Genres                       https://www.the-numbers.com/movie/Mulgoe-(S-Korea)(2018)

In [187]:
print("Missing genres:",
      metaclean_clean["genre"].isna().sum())

print("\nNumber of unique genre combinations:",
      metaclean_clean["genre"].nunique())

print("\nSample genre values:")
print(
    metaclean_clean["genre"]
    .dropna()
    .head(30)
    .to_string(index=False)
)

Missing genres: 20

Number of unique genre combinations: 1312

Sample genre values:
                                Documentary
Action,Sci-Fi,Drama,Mystery,Thriller,Horror
                       Drama,Comedy,Romance
                       Drama,Comedy,Romance
                              Horror,Comedy
                                      Drama
                                      Drama
                    Adventure,Drama,Fantasy
                       Drama,Comedy,Romance
                                      Drama
                             Comedy,Romance
                              Comedy,Family
               Drama,Mystery,Thriller,Crime
                                      Drama
                             Drama,Thriller
                                Documentary
                   Drama,Thriller,Crime,War
                                Documentary
                     Thriller,Horror,Comedy
                              History,Sport
                      Biography,Documentary
                      Action,Thriller,Crime
                   Action,Drama,History,War
                    Biography,Drama,History
                         Drama,Comedy,Music
         Adventure,Biography,Drama,Thriller
                             Drama,Thriller
                                     Action
                     Fantasy,Comedy,Romance
                  Action,Drama,Thriller,War

In [188]:
# seperating genres into their own row
genre_data = metaclean_clean[
    ["url", "genre"]
].copy()

genre_data = genre_data.dropna(subset=["genre"])

genre_data["genre"] = genre_data["genre"].str.split(",")

genre_data = genre_data.explode("genre")

genre_data["genre"] = genre_data["genre"].str.strip()

print("Rows after splitting genres:", len(genre_data))

print("\nUnique individual genres:",
      genre_data["genre"].nunique())

print("\nIndividual genres:")
print(
    genre_data["genre"]
    .value_counts()
)

Rows after splitting genres: 27055

Unique individual genres: 27

Individual genres:
genre
Drama          6267
Comedy         3318
Thriller       2474
Documentary    2011
Romance        1738
Action         1445
Crime          1325
Adventure      1070
Horror          938
Biography       852
Mystery         839
Fantasy         748
Sci-Fi          695
Family          687
Music           583
History         568
Animation       417
War             397
Sport           292
Musical         197
Western          94
News             72
Short            16
Adult             9
Talk-Show         1
Reality-TV        1
Film-Noir         1
Name: count, dtype: int64

<h3>Creating Genre table</h3>

In [189]:

genre = (
    genre_data[["genre"]]
    .drop_duplicates()
    .sort_values("genre")
    .reset_index(drop=True)
)

genre = genre.rename(columns={"genre": "genre_name"})

genre.insert(
    0,
    "genre_id",
    range(1, len(genre) + 1)
)

print("Number of genres:", len(genre))
print(genre.to_string(index=False))

Number of genres: 27
 genre_id  genre_name
        1      Action
        2       Adult
        3   Adventure
        4   Animation
        5   Biography
        6      Comedy
        7       Crime
        8 Documentary
        9       Drama
       10      Family
       11     Fantasy
       12   Film-Noir
       13     History
       14      Horror
       15       Music
       16     Musical
       17     Mystery
       18        News
       19  Reality-TV
       20     Romance
       21      Sci-Fi
       22       Short
       23       Sport
       24   Talk-Show
       25    Thriller
       26         War
       27     Western

<h3>Creating Movie_Genre</h3>

In [190]:
# Recreating genre data with movie URL
movie_genre_data = metaclean_clean[
    ["url", "genre"]
].copy()

# Remove movies without genre
movie_genre_data = movie_genre_data.dropna(subset=["genre"])

# Split multiple genres into separate rows
movie_genre_data["genre"] = movie_genre_data["genre"].str.split(",")

movie_genre_data = movie_genre_data.explode("genre")

# Clean whitespace
movie_genre_data["genre"] = movie_genre_data["genre"].str.strip()

# Add movie_id using the exact MetaClean URL
movie_genre_data = movie_genre_data.merge(
    movie[["movie_id", "url"]],
    on="url",
    how="inner"
)

# Add genre_id
movie_genre_data = movie_genre_data.merge(
    genre,
    left_on="genre",
    right_on="genre_name",
    how="inner"
)

# Keep only bridge-table columns
movie_genre = movie_genre_data[
    ["movie_id", "genre_id"]
].copy()

# Remove any duplicate movie-genre relationships
movie_genre = movie_genre.drop_duplicates()

# Sort for easier inspection
movie_genre = movie_genre.sort_values(
    ["movie_id", "genre_id"]
).reset_index(drop=True)

print("Movie_Genre rows:", len(movie_genre))
print("Unique movies:", movie_genre["movie_id"].nunique())
print("Unique genres:", movie_genre["genre_id"].nunique())
print("Duplicate relationships:", movie_genre.duplicated().sum())

print("\nFirst 20 rows:")
print(movie_genre.head(20))

Movie_Genre rows: 27051
Unique movies: 11344
Unique genres: 27
Duplicate relationships: 0

First 20 rows:
    movie_id  genre_id
0          1         8
1          2         1
2          2         9
3          2        14
4          2        17
5          2        21
6          2        25
7          3         6
8          3         9
9          3        20
10         4         6
11         4         9
12         4        20
13         5         6
14         5        14
15         6         9
16         7         9
17         8         3
18         8         9
19         8        11

In [191]:
genre.to_csv(
    "Genre.csv",
    index=False,
    encoding="utf-8-sig"
)

movie_genre.to_csv(
    "Movie_Genre.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Genre exported:", genre.shape)
print("Movie_Genre exported:", movie_genre.shape)

Genre exported: (27, 2)
Movie_Genre exported: (27051, 2)

<h3>Building keywords table</h3>

In [192]:
# inspecting keyword
# Inspect the keywords column
keyword_data = sales_clean[["url", "keywords"]].copy()

print("Total rows:", len(keyword_data))
print("Missing keywords:", keyword_data["keywords"].isna().sum())
print("Unique keyword values:", keyword_data["keywords"].nunique())

print("\nSample keyword values:")
print(
    keyword_data["keywords"]
    .dropna()
    .head(30)
    .to_string(index=False)
)

Total rows: 30612
Missing keywords: 18103
Unique keyword values: 1223

Sample keyword values:
                        Coming of Age
                     Foreign Language
                                Heist
                             Haunting
                               Soccer
                              Royalty
                             TV Movie
                 Dysfunctional Family
                               LGBTQ+
                          World War I
                            Religious
                Government Corruption
                 Life in a Small Town
                                  3-D
                       Alien Invasion
                          Animal Lead
             Relationships Gone Wrong
Actors Making Their Directorial Debut
                                  3-D
                          Arab Spring
                     Terminal Illness
                         Set in China
                    Mountain Climbing
                               Trains
                               Soccer
                         Set in India
                              Bigotry
                                1980s
             Investigative Journalist
                            Blindness

In [193]:
# Clean and inspect keyword values
keyword_data = sales_clean[["url", "keywords"]].copy()

keyword_data["keywords"] = (
    keyword_data["keywords"]
    .astype("string")
    .str.strip()
)

# Treat empty strings as missing
keyword_data["keywords"] = keyword_data["keywords"].replace("", pd.NA)

print("Missing keywords after cleaning:", keyword_data["keywords"].isna().sum())
print("Unique keywords after cleaning:", keyword_data["keywords"].nunique())

print("\nAll keyword values:")
print(
    keyword_data["keywords"]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .to_string(index=False)
)

Missing keywords after cleaning: 18103
Unique keywords after cleaning: 1223

All keyword values:
                                           1000s
                                           1200s
                                           1300s
                                           1400s
                                           1500s
                                           1600s
                                           1700s
                                           1800s
                                           1840s
                                           1870s
                                           1880s
                                           1890s
                                           1900s
                                           1910s
                                           1920s
                                           1930s
                                           1940s
                                           1950s
                                           1960s
                                           1970s
                                           1980s
                                           1990s
                                           2000s
                2010 Oscars Best Picture Nominee
                                           2010s
                2011 Oscars Best Picture Nominee
                2015 Oscars Best Picture Nominee
                2016 Oscars Best Picture Nominee
                2020 Oscars Best Picture Nominee
                                           2020s
                2021 Oscars Best Picture Nominee
                2022 Oscars Best Picture Nominee
                     2D Digitally Animated Films
                                             3-D
                3-D - Post-production Conversion
                            96 frames per second
                                            AIDS
                                 Abandoned Child
                              Abandoned Hospital
                              Abandoned Location
                                        Abortion
                                       Academics
                                Accidental Death
               Accidental Engagement or Marriage
                               Accidental Injury
                                     Accountants
                                Action Adventure
                                   Action Comedy
                                   Action Horror
                                 Action Thriller
           Actors Making Their Directorial Debut
                             Adapted as a Comedy
                                       Addiction
                                  Adopted Family
                  Adopted Family Seeking Reunion
  Adult Child Dealing with the Death of a Parent
                          Adult Child of Divorce
                                 Adult Education
                       Advertising and Marketing
                                 Afghanistan War
                               African Americans
                                     Afro-French
                                        Agitprop
                                     Agoraphobia
                                 Alien Abduction
                                Alien Encounters
                                  Alien Invasion
                               Alternate History
                               Alternate Reality
                          Alternate Reality Game
      Alternative Dimensions / Parallel universe
                           Alternative Medicines
                              Amateur Filmmakers
                                         Amputee
                                  Amusement Park
                                      Anarchists
                                   Ancient China
                                    Animal Abuse
                                     Animal Lead
                                   Animal Rights
                                Animals Gone Bad
                              Animated Sequences
                                 Animated Shorts
                                           Anime
                             Anxiety and Phobias
                                     Arab Spring
                                     Archaeology
                                    Architecture
        Archival Footage of Previous Installment
                                 Archive Footage
                                   Arctic Circle
                                     Arms Dealer
                               Arranged Marriage
                                       Art World
                         Artificial Intelligence
                         Artisans vs. Automation
                                         Artists
                                         Asexual
                                 Asian-Americans
                        Aspiring Actress / Actor
                                   Assassination
                                Assisted Suicide
                                       Astronaut
                                         Atheism
                       Athletes Past Their Prime
                                       Australia
                          Australian Aboriginals
                                          Autism
                                     Auto Racing
                                Autobiographical
                                    Autumn Years
                                     Avant Garde
                                     Baby Shower
                                     Babysitters
                                  Bachelor Party
                                     Backpacking
                                       Backstage
                                 Bad Role Models
                                          Ballet
                                Bank Foreclosure
                                    Bank Robbery
                                      Bankruptcy
                           Bare Knuckle Fighting
                                       Bartender
                                        Baseball
                        Based on an UNTRUE Story
                                      Basketball
                             Battle of the Sexes
                                       Beat Cops
                                 Beauty Industry
                                 Beauty Pageants
                                        Betrayal
                                       Big Break
                                         Bigfoot
                                         Bigotry
                                 Bike Messengers
                        Biographical Documentary
                              Biographical Drama
                                       Biography
                                  Birthday Party
                                    Black Comedy
                                 Black Out Drunk
                                     Black Urban
                                      Blind Date
                                       Blindness
                                      Board Game
                                 Boarding School
                                     Body Horror
                                       Body Swap
                                    Bodybuilders
                                       Bodyguard
                                   Bodysnatchers
                                       Bollywood
                        Bonnie and Clyde romance
                                  Boomerang Kids
                                     Border Town
                                  Boss From Hell
                                   Bounty Hunter
                                         Bowling
                                          Boxing
                        Breaking the Fourth Wall
                                        Broadway
                                        Buddhism
                                    Buddy Comedy
                                       Buddy Cop
                                         Bullies
                                    Buried Alive
                                       Burlesque
                                          C.I.A.
                              Cabin in the Woods
                                         Camping
                                          Cancer
                                     Cannibalism
                                    Car Accident
                                       Car Chase
                                        Catholic
                                         Cavemen
                               Celebrity Worship
                                 Chase Adventure
                                    Cheerleaders
                                            Chef
                              Chernobyl Disaster
                                           Chess
                                     Child Abuse
                                     Child Actor
                                     Child Bride
                                  Child Murderer
                                   Child Prodigy
                              Child Prostitution
                                   Child Soldier
                                      Child Star
                               Childhood Friends
                   Children Dealing with Divorce
                               Chinese Mythology
                    Christian Contemporary Music
                                      Christians
                                       Christmas
                           Christmas in November
                                   Cinema Verite
                                       Cinephile
                                          Circus
                              Civil Disobedience
                           Civil Rights Movement
                                       Civil War
                                   Class Warfare
                                 Classical Music
                              Cliffhanger Ending
                                         Cloning
                             Closeted Homosexual
                                          Clowns
                                        Cold War
                     Collectors and Collectables
                                         College
                               College Professor
                                College Reunions
                                  College Sports
                                            Coma
                                    Comedy Drama
                                  Comic Industry
                                   Coming of Age
                             Coming-of-Age Drama
                                       Communism
                              Competitive Eating
                                    Compilations
                                        Composer
                               Computer Industry
                            Computer Screen Film
                                  Confidence Men
                               Conspiracy Theory
                                Cops and Robbers
                                  Corporate Life
                           Corporate Malfeasance
                                    Corrupt Cops
                                   Corrupt Judge
                                  Counterculture
                       Country Mouse, City Mouse
                       Country and Western Music
                                 Courtroom Drama
                                        Cover Up
                 Covering Up an Accidental Death
                                         Cowboys
                         Cowboys in Modern Times
                                Creature Feature
                                         Cricket
                                           Crime
                                      Crime Boss
                                     Crime Caper
                                    Crime Comedy
                                  Crime Thriller
                                     Crime drama
                             Cross-Class Romance
                                  Cross-Dressing
                                    Crowdfunding
                                   Cryptozoology
                                           Cults
                             Cultural Revolution
                                   Culture Clash
                                          Curses
                           Cut from Older Movies
                                         Cycling
                                     D.C. Comics
                                       DEA Agent
                                         Dancing
                                       Daredevil
                               Dark Horse Comics
                                            Deaf
                                   Death Penalty
                                    Death Sports
                            Death as a Character
                  Death of Other Extended Family
                          Death of a Best Friend
               Death of a Girlfriend / Boyfriend
                              Death of a Partner
                                  Death of a Pet
                              Death of a Sibling
                      Death of a Son or Daughter
     Death of a Spouse or FiancÃƒÂ©e / FiancÃƒÂ©
                                 Death of a Twin
                               Delayed Adulthood
                                 Delayed Release
                                  Delayed Sequel
                                          Demons
                                      Depression
                                  Descrimination
                                          Desert
                                  Designer Drugs
                                Development Hell
                          Died During Childbirth
                          Digital Cinematography
                                    Dinner Party
                                       Dinosaurs
                   Dinosaurs in the Modern World
                                 Direct-to-Video
                              Directing Yourself
                                      Disability
                                        Disaster
                  Disrupted by COVID-19 pandemic
                             DivorcÃƒÂ©e Romance
                                         Doctors
                                       Docudrama
                                     Docufiction
                                   Documentarian
                                  Domestic Abuse
                                    Doppelganger
                                     Double Life
                                  Double-Crossed
                                   Down Syndrome
                                          Dragon
                                  Dream Sequence
                                         Drifter
                               Drive-By Shooting
                                        Drop Out
                                    Drug Cartels
                                     Drug Dealer
                                Drug Trafficking
                                    Drunk Driver
                                         Dwarves
                            Dysfunctional Family
                                        Dystopia
    Early / Simultaneous Video-on-Demand release
                                    East Germany
                                          Easter
                                 Eating Disorder
                                     Edutainment
                               Elementary School
                                         Eloping
                             Elvis Impersonators
                                      Empty Nest
                                End of the World
                 Enemies Forced to Work Together
                                        Ensemble
                                    Entrepreneur
                                     Environment
                                        Epidemic
                                        Epilogue
                                      Equestrian
                                    Erotic Drama
                                 Erotic Thriller
                                          Escape
                                 Evil Mastermind
                                          Ex-cop
                                      Ex-soldier
                                           Exile
                                        Exorcism
                               Experimental Film
                         Experimental Treatments
                                        Explorer
                   Exploring a Character's  Mind
                                  Extreme Sports
                                 Extreme Weather
                                         F-Rated
                                             FBI
                                         Fairies
                               Faith-Based Drama
                                Faith-Based Film
                                     Fake Dating
                                     Fake Sports
                               Faked Pregnancies
                                   Faked Romance
                                  False Identity
                                 Falsely Accused
                                Family Adventure
                                   Family Affair
                                   Family Comedy
                                    Family Drama
                                    Family Movie
                                  Family Secrets
                                Family Vacations
                                    Famously Bad
                                Fantasy Sequence
                     Farcical / Slapstick Comedy
                                         Fashion
                                        Fat Suit
                                 Fate or Destiny
                       FatherÃ¢â‚¬â„¢s Footsteps
                                   Faulty Memory
                                        Faustian
                                     Female Lead
                              Female empowerment
                                        Feminism
                     Fiction / Reality Crossover
               Fictionalized Version of Yourself
                                Field Scientists
                                      Film Actor
                                   Film Festival
                                       Film Noir
                           Filmed By a Character
Filmed in Carlo IV Hotel, Prague, Czech Republic
                Filmed in Georgia, United States
                                Filmed in Israel
                         Filmed in Paris, France
  Filmed in Puzzlewood, Gloucestershire, England
                              Filmed in Thailand
                                           Fired
                                     Firefighter
                                   First Contact
                                      First Love
                              First Time Parents
                                Flight Attendant
                                      Folk Music
                                            Food
                                        Football
                                Foreign Language
                         Foreign-Language Remake
                     Former Professional Athlete
                                       Formula 1

In [194]:
# Create Keyword table
keyword = (
    keyword_data[["keywords"]]
    .dropna()
    .drop_duplicates()
    .sort_values("keywords")
    .reset_index(drop=True)
)

keyword = keyword.rename(columns={"keywords": "keyword_name"})

keyword.insert(
    0,
    "keyword_id",
    range(1, len(keyword) + 1)
)

print("Number of keywords:", len(keyword))
print("\nDuplicate keyword IDs:", keyword["keyword_id"].duplicated().sum())
print("Missing keyword names:", keyword["keyword_name"].isna().sum())

print("\nFirst 30 keywords:")
print(keyword.head(30).to_string(index=False))

Number of keywords: 1223

Duplicate keyword IDs: 0
Missing keyword names: 0

First 30 keywords:
 keyword_id                     keyword_name
          1                            1000s
          2                            1200s
          3                            1300s
          4                            1400s
          5                            1500s
          6                            1600s
          7                            1700s
          8                            1800s
          9                            1840s
         10                            1870s
         11                            1880s
         12                            1890s
         13                            1900s
         14                            1910s
         15                            1920s
         16                            1930s
         17                            1940s
         18                            1950s
         19                            1960s
         20                            1970s
         21                            1980s
         22                            1990s
         23                            2000s
         24 2010 Oscars Best Picture Nominee
         25                            2010s
         26 2011 Oscars Best Picture Nominee
         27 2015 Oscars Best Picture Nominee
         28 2016 Oscars Best Picture Nominee
         29 2020 Oscars Best Picture Nominee
         30                            2020s

In [195]:
# Prepare keyword data with title and year for matching
movie_keyword_data = sales_clean[
    ["title", "year", "keywords"]
].copy()

# Clean keyword values
movie_keyword_data["keywords"] = (
    movie_keyword_data["keywords"]
    .astype("string")
    .str.strip()
)

# Remove missing keywords
movie_keyword_data = movie_keyword_data.dropna(subset=["keywords"])

# Create matching title
movie_keyword_data["title_match"] = (
    movie_keyword_data["title"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Match Sales records to Movie
movie_keyword_data = movie_keyword_data.merge(
    movie_match[["movie_id", "title_match", "year"]],
    on=["title_match", "year"],
    how="inner"
)

# Match keywords to Keyword table
movie_keyword_data = movie_keyword_data.merge(
    keyword,
    left_on="keywords",
    right_on="keyword_name",
    how="inner"
)

# Keep bridge-table columns
movie_keyword = movie_keyword_data[
    ["movie_id", "keyword_id"]
].drop_duplicates()

# Sort
movie_keyword = movie_keyword.sort_values(
    ["movie_id", "keyword_id"]
).reset_index(drop=True)

print("Movie_Keyword rows:", len(movie_keyword))
print("Unique movies:", movie_keyword["movie_id"].nunique())
print("Unique keywords:", movie_keyword["keyword_id"].nunique())
print("Duplicate relationships:", movie_keyword.duplicated().sum())

print("\nFirst 20 rows:")
print(movie_keyword.head(20))

Movie_Keyword rows: 6090
Unique movies: 6086
Unique keywords: 881
Duplicate relationships: 0

First 20 rows:
    movie_id  keyword_id
0          2         538
1          4         331
2          5          43
3          9         827
4         10         970
5         12         561
6         13         570
7         19          22
8         20        1052
9         23          23
10        24        1031
11        26         576
12        29         149
13        30         940
14        32         404
15        33         386
16        37         249
17        38         233
18        40        1079
19        51         320

In [196]:
keyword.to_csv(
    "Keyword.csv",
    index=False,
    encoding="utf-8-sig"
)

movie_keyword.to_csv(
    "Movie_Keyword.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Keyword exported:", keyword.shape)
print("Movie_Keyword exported:", movie_keyword.shape)

Keyword exported: (1223, 2)
Movie_Keyword exported: (6090, 2)

<h4>Inspecting the columns needed for Actor table</h4>

In [197]:
actor_data = metaclean_clean[["url", "cast"]].copy()

print("Total rows:", len(actor_data))
print("Missing cast:", actor_data["cast"].isna().sum())
print("Unique cast values:", actor_data["cast"].nunique())

print("\nSample cast values:")
print(
    actor_data["cast"]
    .dropna()
    .head(20)
    .to_string(index=False)
)

Total rows: 11364
Missing cast: 3702
Unique cast values: 7593

Sample cast values:
John Gallagher Jr.,John Goodman,Mary Elizabeth ...
                Jonah Hill,Morgan Freeman,Paz Vega
            Channing Tatum,Chris Pratt,Jenna Dewan
            Camilla Belle,Marco Khan,Steven Strait
             Hilmir SnÃ¦r GuÃ°nason,Victoria Abril
                     GÃ©rard Depardieu,Glenn Close
         Brad Renfro,Giovanni Ribisi,James Marsden
                                        Abby Linne
    Apti Magamaev,Sergei Makovetsky,Sergey Garmash
Angela Bettis,Brooke Seguin,Chloe Farnworth,Dav...
Carlson Young,Jacob Lofland,Jake Austin Walker,...
                            Ashley Scott,John Cena
Austin HÃ©bert,Austin Stowell,Ben O'Toole,Chris...
Alfre Woodard,Benedict Cumberbatch,Brad Pitt,Ch...
              Amber Tamblyn,James Franco,Kate Mara
           Jennifer Garner,Judy Greer,Mark Ruffalo
Alexia Barlier,David Costabile,David Denman,Jam...
Burghart KlauÃner,Christian Friedel,Cornelia K...
                                   George Babluani
      John Cusack,Mary McCormack,Samuel L. Jackson

In [198]:
actor_data = metaclean_clean[["url", "cast"]].copy()

# Remove movies without cast information
actor_data = actor_data.dropna(subset=["cast"])

# Split comma-separated actors into individual rows
actor_data["cast"] = actor_data["cast"].str.split(",")

actor_data = actor_data.explode("cast")

# Clean whitespace
actor_data["cast"] = actor_data["cast"].str.strip()

# Remove empty actor names, if any
actor_data = actor_data[actor_data["cast"] != ""]

print("Rows after splitting actors:", len(actor_data))
print("Unique actors:", actor_data["cast"].nunique())

print("\nTop 30 actors by number of appearances:")
print(
    actor_data["cast"]
    .value_counts()
    .head(30)
)

Rows after splitting actors: 48296
Unique actors: 24861

Top 30 actors by number of appearances:
cast
Samuel L. Jackson      47
Morgan Freeman         45
Nicolas Cage           43
Julianne Moore         42
Liam Neeson            42
Willem Dafoe           40
Colin Farrell          38
Matt Damon             38
Mark Wahlberg          37
Ethan Hawke            37
Robert De Niro         36
Naomi Watts            36
Scarlett Johansson     35
Johnny Depp            35
Cate Blanchett         35
James Franco           34
Bruce Willis           34
Ewan McGregor          34
Nicole Kidman          34
Jude Law               33
Ryan Reynolds          33
Dwayne Johnson         33
Charlize Theron        32
Alec Baldwin           32
Matthew McConaughey    32
Gerard Butler          31
Owen Wilson            31
Hugh Jackman           31
John Cusack            30
Adam Sandler           30
Name: count, dtype: int64

<h4>Creating Actor table</h4>

In [199]:
actor = (
    actor_data[["cast"]]
    .drop_duplicates()
    .sort_values("cast")
    .reset_index(drop=True)
)

actor = actor.rename(columns={"cast": "actor_name"})

actor.insert(
    0,
    "actor_id",
    range(1, len(actor) + 1)
)

print("Number of actors:", len(actor))
print("Duplicate actor IDs:", actor["actor_id"].duplicated().sum())
print("Missing actor names:", actor["actor_name"].isna().sum())

print("\nFirst 30 actors:")
print(actor.head(30).to_string(index=False))

Number of actors: 24861
Duplicate actor IDs: 0
Missing actor names: 0

First 30 actors:
 actor_id        actor_name
        1           50 Cent
        2           6ix9ine
        3        A Martinez
        4  A. Brian Daniels
        5 A. Patrice Moreau
        6         A.J. Cook
        7          AJ Bowen
        8            AJ Dee
        9         AJ Meijer
       10         AJ Slaght
       11      Aakash Sinha
       12           Aaliyah
       13     Aaliyah Lopez
       14       Aalok Mehta
       15      Aaron Abrams
       16     Aaron Altaras
       17     Aaron Ashmore
       18    Aaron Augustus
       19     Aaron Beelner
       20     Aaron Blakely
       21       Aaron Burns
       22       Aaron Cohen
       23 Aaron Costa Ganis
       24     Aaron Crippen
       25 Aaron Dalla Villa
       26     Aaron Dessner
       27     Aaron Douglas
       28     Aaron Eckhart
       29      Aaron Fisher
       30        Aaron Gain

<h3>Creating the Movie_Actor</h3>

In [200]:
# Match actors back to Movie using the exact MetaClean URL
movie_actor_data = actor_data.merge(
    movie[["movie_id", "url"]],
    on="url",
    how="inner"
)

# Match actor names to Actor table
movie_actor_data = movie_actor_data.merge(
    actor,
    left_on="cast",
    right_on="actor_name",
    how="inner"
)

# Keep only bridge-table columns
movie_actor = movie_actor_data[
    ["movie_id", "actor_id"]
].drop_duplicates()

# Sort for easier inspection
movie_actor = movie_actor.sort_values(
    ["movie_id", "actor_id"]
).reset_index(drop=True)

print("Movie_Actor rows:", len(movie_actor))
print("Unique movies:", movie_actor["movie_id"].nunique())
print("Unique actors:", movie_actor["actor_id"].nunique())
print("Duplicate relationships:", movie_actor.duplicated().sum())

print("\nFirst 20 rows:")
print(movie_actor.head(20))

Movie_Actor rows: 48284
Unique movies: 7662
Unique actors: 24861
Duplicate relationships: 0

First 20 rows:
    movie_id  actor_id
0          2     11724
1          2     11732
2          2     16026
3          3     11939
4          3     17414
5          3     18974
6          4      4073
7          4      4417
8          4     10964
9          8      3655
10         8     15506
11         8     22360
12        11      9398
13        11     23905
14        12      8654
15        12      8925
16        13      3109
17        13      8622
18        13     10383
19        16        72

In [201]:
actor.to_csv(
    "Actor.csv",
    index=False,
    encoding="utf-8-sig"
)

movie_actor.to_csv(
    "Movie_Actor.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Actor exported:", actor.shape)
print("Movie_Actor exported:", movie_actor.shape)

Actor exported: (24861, 2)
Movie_Actor exported: (48284, 2)

<h3>Building Director table</h3>

In [202]:
# verifying if there is only one director per movie
director_data = metaclean_clean[["url", "director"]].copy()

print("Total rows:", len(director_data))
print("Missing directors:", director_data["director"].isna().sum())
print("Unique director values:", director_data["director"].nunique())

print("\nSample director values:")
print(
    director_data["director"]
    .dropna()
    .head(30)
    .to_string(index=False)
)

Total rows: 11364
Missing directors: 14
Unique director values: 6136

Sample director values:
 Lynn Hershman-Leeson
     Dan Trachtenberg
      Brad Silberling
         Jamie Linden
      Cameron Cairnes
         Jim O'Hanlon
           Erik Poppe
      Roland Emmerich
Carlos Marques-Marcet
           Bent Hamer
   Baltasar KormÃ¡kur
           Kevin Lima
       Robert Moresco
       Xiaoshuai Wang
    Jerzy Skolimowski
       Alison Klayman
     Nikita Mikhalkov
         Amir Bar-Lev
           Brea Grant
           Ty Roberts
         Lotfy Nathan
         Renny Harlin
      Nicolai Fuglsig
        Steve McQueen
   Corneliu Porumboiu
          Danny Boyle
       GÃ©la Babluani
       Takashi  Miike
          Gary Winick
          Michael Bay

In [203]:
# Clean director names
director_data["director"] = (
    director_data["director"]
    .astype("string")
    .str.strip()
)

# Treat empty strings as missing
director_data["director"] = director_data["director"].replace("", pd.NA)

# Create Director table
director = (
    director_data[["director"]]
    .dropna()
    .drop_duplicates()
    .sort_values("director")
    .reset_index(drop=True)
)

director = director.rename(
    columns={"director": "director_name"}
)

director.insert(
    0,
    "director_id",
    range(1, len(director) + 1)
)

print("Number of directors:", len(director))
print("Duplicate director IDs:", director["director_id"].duplicated().sum())
print("Missing director names:", director["director_name"].isna().sum())

print("\nFirst 30 directors:")
print(director.head(30).to_string(index=False))

Number of directors: 6136
Duplicate director IDs: 0
Missing director names: 0

First 30 directors:
 director_id           director_name
           1            A. Dean Bell
           2             A.B. Shawky
           3              A.J. Eaton
           4            A.J. Edwards
           5              AJ Schnack
           6             Aaron Aites
           7         Aaron B. Koontz
           8            Aaron Blaise
           9          Aaron Brookner
          10            Aaron Fisher
          11            Aaron Harvey
          12           Aaron Horvath
          13              Aaron Katz
          14              Aaron Kopp
          15          Aaron Moorhead
          16               Aaron Nee
          17              Aaron Rose
          18             Aaron Russo
          19         Aaron Schimberg
          20         Aaron Schneider
          21            Aaron Schock
          22           Aaron Seltzer
          23            Aaron Sorkin
          24         Aaron Wickenden
          25           Aaron Woodley
          26             Aaron Woolf
          27 AarÃ³n FernÃ¡ndez Lesur
          28        Abbas Kiarostami
          29            Abby Epstein
          30               Abby Kohn

<h3>Building Movie_Director</h3>

In [204]:
# Match directors to Movie using the exact MetaClean URL
movie_director_data = director_data.merge(
    movie[["movie_id", "url"]],
    on="url",
    how="inner"
)

# Match director names to Director table
movie_director_data = movie_director_data.merge(
    director,
    left_on="director",
    right_on="director_name",
    how="inner"
)

# Keep bridge-table columns
movie_director = movie_director_data[
    ["movie_id", "director_id"]
].drop_duplicates()

# Sort
movie_director = movie_director.sort_values(
    ["movie_id", "director_id"]
).reset_index(drop=True)

print("Movie_Director rows:", len(movie_director))
print("Unique movies:", movie_director["movie_id"].nunique())
print("Unique directors:", movie_director["director_id"].nunique())
print("Duplicate relationships:", movie_director.duplicated().sum())

print("\nFirst 20 rows:")
print(movie_director.head(20))

Movie_Director rows: 11350
Unique movies: 11350
Unique directors: 6136
Duplicate relationships: 0

First 20 rows:
    movie_id  director_id
0          1         3798
1          2         1380
2          3          804
3          4         2640
4          5          927
5          6         2922
6          7         1954
7          8         5138
8          9          959
9         10          697
10        11          604
11        12         3485
12        13         5079
13        14         6052
14        15         2867
15        16          254
16        17         4519
17        18          287
18        19          819
19        20         5898

In [205]:
director.to_csv(
    "Director.csv",
    index=False,
    encoding="utf-8-sig"
)

movie_director.to_csv(
    "Movie_Director.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Director exported:", director.shape)
print("Movie_Director exported:", movie_director.shape)

Director exported: (6136, 2)
Movie_Director exported: (11350, 2)

Additional Cleaning after Importing files

In [ ]:
# cleaning the data type of theater_count column in Movie_Sales
import pandas as pd
df = pd.read_csv("movie_sales.csv")

df["theatre_count"] = df["theatre_count"].astype("Int64")

df.to_csv("Movie_Sales_cleaned.csv", index=False)

In [ ]:
import pandas as pd

df = pd.read_csv("Movie_Characteristics.csv")

df["runtime"] = df["runtime"].astype("Int64")

df.to_csv(
    "Movie_Characteristics_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

In [ ]:

import pandas as pd

df = pd.read_csv("Consumer_Reviews.csv")

df["thumbs_up"] = df["thumbs_up"].astype("Int64")
df["thumbs_total"] = df["thumbs_total"].astype("Int64")

df.to_csv(
    "Consumer_Reviews_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

In [17]:
import pandas as pd

df = pd.read_csv("Expert_Review.csv")

print(df.columns.tolist())

df.info()

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_17804\1172055251.py:3: DtypeWarning: Columns (0: review_date) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Expert_Review.csv")

['expert_review_id', 'url', 'review_score', 'reviewer', 'review_date', 'review_text', 'WC', 'Analytic', 'Clout', 'Authentic', 'Tone', 'WPS', 'Sixltr', 'Dic', 'function', 'pronoun', 'ppron', 'i', 'we', 'you', 'shehe', 'they', 'ipron', 'article', 'prep', 'auxverb', 'adverb', 'conj', 'negate', 'verb', 'adj', 'compare', 'interrog', 'number', 'quant', 'affect', 'posemo', 'negemo', 'anx', 'anger', 'sad', 'social', 'family', 'friend', 'female', 'male', 'cogproc', 'insight', 'cause', 'discrep', 'tentat', 'certain', 'differ', 'percept', 'see', 'hear', 'feel', 'bio', 'body', 'health', 'sexual', 'ingest', 'drives', 'affiliation', 'achieve', 'power', 'reward', 'risk', 'focuspast', 'focuspresent', 'focusfuture', 'relativ', 'motion', 'space', 'time', 'work', 'leisure', 'home', 'money', 'relig', 'death', 'informal', 'swear', 'netspeak', 'assent', 'nonflu', 'filler', 'AllPunc', 'Period', 'Comma', 'Colon', 'SemiC', 'QMark', 'Exclam', 'Dash', 'Quote', 'Apostro', 'Parenth', 'OtherP', 'movie_id']
<class 'pandas.DataFrame'>
RangeIndex: 238946 entries, 0 to 238945
Data columns (total 100 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   expert_review_id  238946 non-null  int64
 1   url               238946 non-null  str
 2   review_score      238944 non-null  float64
 3   reviewer          213737 non-null  str
 4   review_date       134474 non-null  str
 5   review_text       234388 non-null  str
 6   WC                238946 non-null  int64
 7   Analytic          238946 non-null  float64
 8   Clout             238946 non-null  float64
 9   Authentic         238946 non-null  float64
 10  Tone              238946 non-null  float64
 11  WPS               238946 non-null  float64
 12  Sixltr            238946 non-null  float64
 13  Dic               238946 non-null  float64
 14  function          238946 non-null  float64
 15  pronoun           238946 non-null  float64
 16  ppron             238946 non-null  float64
 17  i                 238946 non-null  float64
 18  we                238946 non-null  float64
 19  you               238946 non-null  float64
 20  shehe             238946 non-null  float64
 21  they              238946 non-null  float64
 22  ipron             238946 non-null  float64
 23  article           238946 non-null  float64
 24  prep              238946 non-null  float64
 25  auxverb           238946 non-null  float64
 26  adverb            238946 non-null  float64
 27  conj              238946 non-null  float64
 28  negate            238946 non-null  float64
 29  verb              238946 non-null  float64
 30  adj               238946 non-null  float64
 31  compare           238946 non-null  float64
 32  interrog          238946 non-null  float64
 33  number            238946 non-null  float64
 34  quant             238946 non-null  float64
 35  affect            238946 non-null  float64
 36  posemo            238946 non-null  float64
 37  negemo            238946 non-null  float64
 38  anx               238946 non-null  float64
 39  anger             238946 non-null  float64
 40  sad               238946 non-null  float64
 41  social            238946 non-null  float64
 42  family            238946 non-null  float64
 43  friend            238946 non-null  float64
 44  female            238946 non-null  float64
 45  male              238946 non-null  float64
 46  cogproc           238946 non-null  float64
 47  insight           238946 non-null  float64
 48  cause             238946 non-null  float64
 49  discrep           238946 non-null  float64
 50  tentat            238946 non-null  float64
 51  certain           238946 non-null  float64
 52  differ            238946 non-null  float64
 53  percept           238946 non-null  float64
 54  see               238946 non-null  float64
 55  hear              238946 non-null  float64
 56  feel              238946 non-null  float64
 57  bio               238946 non-null  float64
 58  body              238946 non-null  float64
 59  health            238946 non-null  float64
 60  sexual            238946 non-null  float64
 61  ingest            238946 non-null  float64
 62  drives            238946 non-null  float64
 63  affiliation       238946 non-null  float64
 64  achieve           238946 non-null  float64
 65  power             238946 non-null  float64
 66  reward            238946 non-null  float64
 67  risk              238946 non-null  float64
 68  focuspast         238946 non-null  float64
 69  focuspresent      238946 non-null  float64
 70  focusfuture       238946 non-null  float64
 71  relativ           238946 non-null  float64
 72  motion            238946 non-null  float64
 73  space             238946 non-null  float64
 74  time              238946 non-null  float64
 75  work              238946 non-null  float64
 76  leisure           238946 non-null  float64
 77  home              238946 non-null  float64
 78  money             238946 non-null  float64
 79  relig             238946 non-null  float64
 80  death             238946 non-null  float64
 81  informal          238946 non-null  float64
 82  swear             238946 non-null  float64
 83  netspeak          238946 non-null  float64
 84  assent            238946 non-null  float64
 85  nonflu            238946 non-null  float64
 86  filler            238946 non-null  float64
 87  AllPunc           238946 non-null  float64
 88  Period            238946 non-null  float64
 89  Comma             238946 non-null  float64
 90  Colon             238946 non-null  float64
 91  SemiC             238946 non-null  float64
 92  QMark             238946 non-null  float64
 93  Exclam            238946 non-null  float64
 94  Dash              238946 non-null  float64
 95  Quote             238946 non-null  int64
 96  Apostro           238946 non-null  float64
 97  Parenth           238946 non-null  float64
 98  OtherP            238946 non-null  float64
 99  movie_id          238946 non-null  int64
dtypes: float64(92), int64(4), str(4)
memory usage: 182.3 MB